name = "ganger-call-center-ops"
main = "worker-simple.js"
compatibility_date = "2024-06-12"
compatibility_flags = ["nodejs_compat"]

[env.production]
name = "ganger-call-center-ops-prod"
# Routes handled by staff-router.js at staff.gangerdermatology.com/call-center-ops

[env.staging]
name = "ganger-call-center-ops-staging"

# Environment variables
[vars]
ENVIRONMENT = "production"
APP_NAME = "Call Center Operations"