name = "ganger-call-center-ops-v2"
main = "worker.js"
compatibility_date = "2024-01-01"

[[r2_buckets]]
binding = "CALL_CENTER_OPS_BUCKET"
bucket_name = "ganger-call-center-ops"
preview_bucket_name = "ganger-call-center-ops-preview"

[env.production]
name = "ganger-call-center-ops-v2"

[[env.production.r2_buckets]]
binding = "CALL_CENTER_OPS_BUCKET"
bucket_name = "ganger-call-center-ops-production"

[env.staging]
name = "ganger-call-center-ops-staging"

[[env.staging.r2_buckets]]
binding = "CALL_CENTER_OPS_BUCKET"
bucket_name = "ganger-call-center-ops-staging"