name = "ganger-eos-l10"
main = "worker-simple.js"
compatibility_date = "2024-06-12"
compatibility_flags = ["nodejs_compat"]

[env.production]
name = "ganger-eos-l10-prod"
# Routes handled by staff-router.js at staff.gangerdermatology.com/l10

[env.staging]
name = "ganger-eos-l10-staging"

# Environment variables
[vars]
ENVIRONMENT = "production"
APP_NAME = "EOS L10 System"