name = "ganger-medication-auth-prod"
compatibility_date = "2024-12-13"
main = "worker.js"

[env.production]
name = "ganger-medication-auth-prod"

[env.staging]
name = "ganger-medication-auth-staging"

[env.production.vars]
ENVIRONMENT = "production"
APP_NAME = "medication-auth"