#!/usr/bin/env python3
"""
Find all database schema changes between original and new schema
This will help identify what needs to be fixed in the codebase
"""

import re
import os
import json

# Define the changes made
SCHEMA_CHANGES = {
    "table_renames": {
        # Original -> New (if any tables were renamed)
        "users": "profiles",  # The original had both, but we consolidated
    },
    
    "column_changes": {
        "audit_logs": {
            "timestamp": "created_at",  # Changed reserved word
            "metadata": "details",      # Possible rename
            "resource_id": "resource_id",  # Changed from UUID to TEXT in some versions
        },
        "profiles": {
            "position": '"position"',   # Now quoted due to reserved word
        },
    },
    
    "removed_tables": [
        # Tables that existed in original but not in clean schema
        "staff_tickets",  # Renamed to "tickets"
        "staff_approvals",
        "staff_file_uploads", 
        "staff_job_queue",
        "staff_login_attempts",
        "staff_notifications",
        "staff_pending_hires",
        "user_profiles",  # Consolidated into "profiles"
        "locations",
        "providers",
        "provider_schedules",
        "appointment_types",
        "holidays",
        "operating_hours",
        "break_times",
        "system_settings",
        "notification_templates",
        "notification_logs",
        "email_templates",
        "sms_templates",
        "analytics_events",
        "performance_metrics",
        "error_logs",
        "background_jobs",
        "job_logs",
        "workflow_templates",
        "workflow_instances",
        "workflow_steps",
        "form_templates",
        "form_submissions",
        "document_templates",
        "generated_documents",
        "signature_requests",
        "signed_documents",
        "payment_methods",
        "payment_transactions",
        "refunds",
        "insurance_providers",
        "insurance_plans",
        "coverage_details",
        "claim_submissions",
        "patient_records",
        "medical_history",
        "medications",
        "allergies",
        "vitals",
        "lab_results",
        "lab_orders",
        "imaging_orders",
        "imaging_results",
        "referrals",
        "consultations",
        "treatment_plans",
        "care_team_members",
        "patient_notes",
        "clinical_notes",
        "prescription_templates",
        "prescriptions",
        "prescription_fills",
        "vaccine_inventory",
        "vaccine_administrations",
        "immunization_records",
        "screening_protocols",
        "screening_results",
        "risk_assessments",
        "care_gaps",
        "quality_measures",
        "measure_results",
        "reporting_periods",
        "regulatory_submissions",
        "audit_trail",
        "access_logs",
        "phi_access_logs",
        "security_events",
        "incident_reports",
        "investigations",
        "corrective_actions",
        "training_records",
        "competency_assessments",
        "credentialing_documents",
        "license_tracking",
        "certification_tracking",
        "continuing_education",
        "peer_reviews",
        "performance_evaluations",
        "feedback_surveys",
        "survey_responses",
        "patient_satisfaction",
        "outcome_measures",
        "clinical_outcomes",
        "operational_metrics",
        "financial_metrics",
        "dashboard_configs",
        "report_templates",
        "scheduled_reports",
        "data_exports",
        "integration_mappings",
        "hl7_messages",
        "fhir_resources",
        "api_logs",
        "webhook_events",
        "webhook_deliveries",
        "notification_preferences",
        "communication_preferences",
        "consent_forms",
        "consent_records",
        "release_authorizations",
        "record_requests",
        "record_releases",
        "billing_rules",
        "charge_capture",
        "charge_review",
        "billing_queue",
        "claim_batches",
        "remittance_advice",
        "payment_posting",
        "denial_management",
        "appeal_tracking",
        "collection_accounts",
        "payment_plans",
        "financial_assistance",
        "charity_care",
        "inventory_categories",
        "inventory_locations",
        "inventory_counts",
        "inventory_adjustments",
        "purchase_orders",
        "purchase_order_items",
        "vendor_catalogs",
        "vendor_contracts",
        "supply_requests",
        "supply_fulfillment",
        "equipment_inventory",
        "equipment_maintenance",
        "maintenance_schedules",
        "work_orders",
        "facility_issues",
        "safety_incidents",
        "risk_matrix",
        "mitigation_plans",
        "compliance_tasks",
        "compliance_reviews",
        "policy_documents",
        "procedure_documents",
        "acknowledgments",
        "distribution_lists",
        "communication_logs",
        "announcement_boards",
        "suggestion_box",
        "improvement_ideas",
        "project_tracking",
        "milestone_tracking",
        "resource_allocation",
        "capacity_planning",
        "staffing_patterns",
        "shift_templates",
        "shift_swaps",
        "overtime_tracking",
        "productivity_metrics",
        "utilization_reports",
        "revenue_cycle_metrics",
        "ar_aging",
        "collection_metrics",
        "payer_performance",
        "contract_performance",
        "negotiation_tracking",
        "credentialing_applications",
        "payer_enrollments",
        "provider_networks",
        "referral_patterns",
        "referral_sources",
        "marketing_campaigns",
        "campaign_metrics",
        "lead_tracking",
        "conversion_metrics",
        "retention_metrics",
        "churn_analysis",
        "cohort_analysis",
        "predictive_models",
        "risk_scores",
        "stratification_results",
        "intervention_tracking",
        "outcome_tracking",
        "cost_analysis",
        "roi_calculations",
        "budget_tracking",
        "variance_reports",
        "forecast_models",
        "scenario_planning",
        "strategic_initiatives",
        "kpi_tracking",
        "scorecard_metrics",
        "benchmark_data",
        "industry_comparisons",
        "best_practices",
        "research_studies",
        "clinical_trials",
        "study_participants",
        "data_collection_forms",
        "research_data",
        "analysis_results",
        "publication_tracking",
        "grant_tracking",
        "funding_sources",
        "budget_allocations",
        "expense_tracking",
        "reimbursement_requests",
        "travel_expenses",
        "conference_tracking",
        "presentation_materials",
        "educational_content",
        "learning_modules",
        "assessment_questions",
        "completion_tracking",
        "certificate_generation",
        "cme_tracking",
        "accreditation_tracking",
        "quality_indicators",
        "performance_indicators",
        "clinical_indicators",
        "operational_indicators",
        "financial_indicators",
        "strategic_indicators",
        "balanced_scorecards",
        "strategy_maps",
        "initiative_tracking",
        "action_plans",
        "accountability_matrix",
        "review_cycles",
        "governance_structures",
        "committee_tracking",
        "meeting_minutes",
        "decision_tracking",
        "policy_reviews",
        "compliance_audits",
        "audit_findings",
        "corrective_action_plans",
        "follow_up_tracking",
        "evidence_collection",
        "documentation_requirements",
        "regulatory_changes",
        "impact_assessments",
        "implementation_plans",
        "training_materials",
        "communication_plans",
        "stakeholder_engagement",
        "feedback_collection",
        "survey_design",
        "response_tracking",
        "analysis_reports",
        "improvement_plans",
        "pdsa_cycles",
        "lean_projects",
        "six_sigma_projects",
        "kaizen_events",
        "value_stream_maps",
        "process_maps",
        "workflow_diagrams",
        "standard_work",
        "work_instructions",
        "visual_management",
        "metric_boards",
        "huddle_boards",
        "escalation_processes",
        "issue_tracking",
        "resolution_tracking",
        "root_cause_analysis",
        "failure_modes",
        "control_plans",
        "monitoring_plans",
        "sustainability_plans",
        "knowledge_base",
        "best_practice_library",
        "lesson_learned",
        "case_studies",
        "success_stories",
        "recognition_tracking",
        "award_nominations",
        "achievement_tracking",
        "milestone_celebrations",
        "team_building_events",
        "culture_surveys",
        "engagement_metrics",
        "retention_strategies",
        "recruitment_tracking",
        "onboarding_checklists",
        "orientation_tracking",
        "mentorship_programs",
        "career_development",
        "succession_planning",
        "talent_reviews",
        "performance_calibration",
        "compensation_reviews",
        "benefit_utilization",
        "wellness_programs",
        "health_assessments",
        "biometric_screening",
        "health_coaching",
        "behavior_change",
        "program_participation",
        "outcome_measurements",
        "roi_tracking",
        "vendor_performance",
        "contract_compliance",
        "sla_tracking",
        "issue_escalation",
        "relationship_management",
        "stakeholder_mapping",
        "communication_matrices",
        "raci_charts",
        "project_charters",
        "business_cases",
        "feasibility_studies",
        "risk_registers",
        "issue_logs",
        "change_requests",
        "approval_workflows",
        "sign_off_tracking",
        "document_control",
        "version_tracking",
        "distribution_tracking",
        "retention_schedules",
        "destruction_tracking",
        "archive_management",
        "retrieval_requests",
        "chain_of_custody",
        "evidence_tracking",
        "litigation_holds",
        "discovery_requests",
        "production_tracking",
        "privilege_logs",
        "matter_tracking",
        "outside_counsel",
        "legal_spend",
        "invoice_review",
        "budget_tracking",
        "accrual_tracking",
        "matter_outcomes",
        "precedent_tracking",
        "contract_repository",
        "obligation_tracking",
        "renewal_tracking",
        "amendment_tracking",
        "termination_tracking",
        "dispute_tracking",
        "resolution_agreements",
        "settlement_tracking",
        "payment_schedules",
        "compliance_monitoring",
        "audit_schedules",
        "finding_tracking",
        "remediation_plans",
        "testing_protocols",
        "validation_results",
        "change_control",
        "release_management",
        "deployment_tracking",
        "rollback_plans",
        "incident_management",
        "problem_management",
        "known_errors",
        "workaround_tracking",
        "service_requests",
        "catalog_items",
        "fulfillment_tracking",
        "satisfaction_tracking",
        "sla_compliance",
        "availability_tracking",
        "performance_tracking",
        "capacity_tracking",
        "demand_forecasting",
        "resource_planning",
        "skill_inventories",
        "training_needs",
        "development_plans",
        "certification_requirements",
        "compliance_training",
        "mandatory_training",
        "elective_training",
        "external_training",
        "conference_attendance",
        "professional_development",
        "tuition_reimbursement",
        "scholarship_tracking",
        "grant_applications",
        "award_tracking",
        "recognition_programs",
        "peer_nominations",
        "leadership_awards",
        "service_awards",
        "milestone_recognition",
        "retirement_tracking",
        "exit_interviews",
        "alumni_tracking",
        "rehire_eligibility",
        "reference_checks",
        "background_checks",
        "drug_screening",
        "health_screening",
        "immunization_compliance",
        "tb_testing",
        "fit_testing",
        "safety_training",
        "emergency_preparedness",
        "drill_tracking",
        "incident_command",
        "communication_trees",
        "resource_inventories",
        "supply_caches",
        "vendor_agreements",
        "mutual_aid_agreements",
        "transfer_agreements",
        "collaboration_agreements",
        "data_sharing_agreements",
        "business_associate_agreements",
        "vendor_assessments",
        "risk_assessments",
        "security_assessments",
        "penetration_testing",
        "vulnerability_scanning",
        "patch_management",
        "configuration_management",
        "asset_inventory",
        "software_licenses",
        "hardware_inventory",
        "network_diagrams",
        "system_documentation",
        "disaster_recovery",
        "backup_tracking",
        "restore_testing",
        "failover_testing",
        "tabletop_exercises",
        "after_action_reviews",
        "improvement_tracking",
        "capability_maturity",
        "process_maturity",
        "organizational_maturity",
        "culture_assessments",
        "change_readiness",
        "adoption_tracking",
        "resistance_management",
        "communication_effectiveness",
        "training_effectiveness",
        "knowledge_transfer",
        "documentation_quality",
        "process_adherence",
        "compliance_rates",
        "error_rates",
        "rework_rates",
        "efficiency_metrics",
        "effectiveness_metrics",
        "quality_metrics",
        "safety_metrics",
        "patient_experience_metrics",
        "staff_experience_metrics",
        "physician_experience_metrics",
        "community_benefit",
        "charity_care_tracking",
        "uncompensated_care",
        "community_programs",
        "health_fairs",
        "screening_events",
        "education_programs",
        "support_groups",
        "resource_centers",
        "patient_navigation",
        "care_coordination",
        "transition_planning",
        "discharge_planning",
        "follow_up_tracking",
        "readmission_tracking",
        "prevention_programs",
        "wellness_initiatives",
        "population_health",
        "risk_stratification",
        "care_management",
        "disease_management",
        "medication_management",
        "adherence_tracking",
        "refill_tracking",
        "interaction_checking",
        "allergy_checking",
        "formulary_checking",
        "prior_auth_tracking",
        "appeal_tracking",
        "denial_reasons",
        "approval_rates",
        "turnaround_times",
        "productivity_tracking",
        "efficiency_tracking",
        "utilization_tracking",
        "capacity_utilization",
        "resource_utilization",
        "room_utilization",
        "equipment_utilization",
        "staff_utilization",
        "provider_productivity",
        "rvu_tracking",
        "panel_sizes",
        "access_metrics",
        "wait_times",
        "cycle_times",
        "throughput_metrics",
        "bottleneck_analysis",
        "constraint_management",
        "optimization_models",
        "simulation_models",
        "predictive_analytics",
        "prescriptive_analytics",
        "machine_learning_models",
        "ai_models",
        "algorithm_tracking",
        "model_performance",
        "bias_monitoring",
        "fairness_metrics",
        "explainability_tracking",
        "governance_frameworks",
        "ethical_guidelines",
        "privacy_controls",
        "consent_management",
        "preference_management",
        "opt_out_tracking",
        "data_retention",
        "data_deletion",
        "audit_trails",
        "access_controls",
        "role_definitions",
        "permission_sets",
        "delegation_tracking",
        "proxy_access",
        "emergency_access",
        "break_glass_tracking",
        "inappropriate_access",
        "sanctions_tracking",
        "training_completion",
        "policy_acknowledgment",
        "annual_reviews",
        "competency_validation",
        "skill_assessments",
        "performance_reviews",
        "goal_tracking",
        "objective_tracking",
        "key_results",
        "milestone_tracking",
        "progress_tracking",
        "achievement_tracking",
        "recognition_tracking",
        "reward_tracking",
        "incentive_tracking",
        "bonus_calculations",
        "merit_increases",
        "promotion_tracking",
        "succession_planning",
        "talent_pipelines",
        "leadership_development",
        "mentorship_tracking",
        "coaching_tracking",
        "feedback_tracking",
        "360_reviews",
        "peer_feedback",
        "patient_feedback",
        "family_feedback",
        "community_feedback",
        "stakeholder_feedback",
        "survey_responses",
        "focus_groups",
        "advisory_councils",
        "patient_councils",
        "family_councils",
        "community_boards",
        "governance_boards",
        "committee_structures",
        "reporting_structures",
        "accountability_structures",
        "decision_rights",
        "approval_authorities",
        "spending_limits",
        "signature_authorities",
        "delegation_authorities",
        "reporting_relationships",
        "organizational_charts",
        "position_descriptions",
        "role_descriptions",
        "responsibility_matrices",
        "competency_models",
        "career_ladders",
        "advancement_paths",
        "development_opportunities",
        "stretch_assignments",
        "project_assignments",
        "committee_assignments",
        "task_force_participation",
        "working_group_participation",
        "community_involvement",
        "professional_involvement",
        "industry_participation",
        "standards_committees",
        "advisory_boards",
        "speaking_engagements",
        "publication_opportunities",
        "research_opportunities",
        "innovation_projects",
        "improvement_projects",
        "transformation_projects",
        "strategic_projects",
        "operational_projects",
        "technology_projects",
        "infrastructure_projects",
        "facility_projects",
        "expansion_projects",
        "renovation_projects",
        "equipment_projects",
        "system_implementations",
        "process_implementations",
        "program_implementations",
        "service_line_development",
        "market_development",
        "partnership_development",
        "affiliation_tracking",
        "joint_venture_tracking",
        "collaboration_tracking",
        "network_development",
        "referral_development",
        "physician_relations",
        "community_relations",
        "government_relations",
        "payer_relations",
        "vendor_relations",
        "partner_relations",
        "investor_relations",
        "media_relations",
        "public_relations",
        "crisis_communications",
        "issue_management",
        "reputation_management",
        "brand_management",
        "marketing_management",
        "advertising_tracking",
        "campaign_tracking",
        "creative_assets",
        "content_management",
        "website_analytics",
        "social_media_tracking",
        "engagement_tracking",
        "conversion_tracking",
        "attribution_tracking",
        "roi_measurement",
        "budget_performance",
        "spend_tracking",
        "vendor_contracts",
        "agency_relationships",
        "freelance_tracking",
        "project_tracking",
        "deliverable_tracking",
        "approval_processes",
        "revision_tracking",
        "version_control",
        "asset_management",
        "rights_management",
        "usage_tracking",
        "license_compliance",
        "copyright_tracking",
        "trademark_tracking",
        "patent_tracking",
        "intellectual_property",
        "trade_secrets",
        "confidentiality_agreements",
        "non_disclosure_agreements",
        "non_compete_agreements",
        "employment_agreements",
        "contractor_agreements",
        "vendor_agreements",
        "customer_agreements",
        "partner_agreements",
        "license_agreements",
        "lease_agreements",
        "purchase_agreements",
        "service_agreements",
        "maintenance_agreements",
        "support_agreements",
        "warranty_tracking",
        "claim_tracking",
        "dispute_resolution",
        "arbitration_tracking",
        "mediation_tracking",
        "litigation_tracking",
        "case_management",
        "document_management",
        "discovery_management",
        "deposition_tracking",
        "witness_tracking",
        "expert_tracking",
        "exhibit_tracking",
        "trial_preparation",
        "settlement_negotiations",
        "judgment_tracking",
        "appeal_tracking",
        "enforcement_tracking",
        "collection_tracking",
        "bankruptcy_tracking",
        "creditor_tracking",
        "asset_tracking",
        "lien_tracking",
        "security_interests",
        "ucc_filings",
        "corporate_records",
        "board_minutes",
        "shareholder_records",
        "stock_tracking",
        "option_tracking",
        "vesting_schedules",
        "exercise_tracking",
        "tax_tracking",
        "compliance_calendar",
        "filing_deadlines",
        "payment_deadlines",
        "reporting_deadlines",
        "renewal_deadlines",
        "expiration_tracking",
        "notification_tracking",
        "reminder_systems",
        "escalation_systems",
        "workflow_systems",
        "integration_platforms",
        "data_warehouses",
        "data_lakes",
        "analytics_platforms",
        "reporting_platforms",
        "visualization_tools",
        "self_service_tools",
        "collaboration_tools",
        "communication_tools",
        "project_tools",
        "workflow_tools",
        "document_tools",
        "knowledge_tools",
        "learning_tools",
        "assessment_tools",
        "survey_tools",
        "feedback_tools",
        "recognition_tools",
        "wellness_tools",
        "safety_tools",
        "compliance_tools",
        "audit_tools",
        "risk_tools",
        "security_tools",
        "monitoring_tools",
        "alerting_tools",
        "incident_tools",
        "problem_tools",
        "change_tools",
        "release_tools",
        "testing_tools",
        "quality_tools",
        "performance_tools",
        "optimization_tools",
        "simulation_tools",
        "modeling_tools",
        "prediction_tools",
        "planning_tools",
        "scheduling_tools",
        "resource_tools",
        "inventory_tools",
        "procurement_tools",
        "vendor_tools",
        "contract_tools",
        "financial_tools",
        "billing_tools",
        "collection_tools",
        "payment_tools",
        "reconciliation_tools",
        "reporting_tools",
        "analytics_tools",
        "dashboard_tools",
        "scorecard_tools",
        "benchmark_tools",
        "comparison_tools",
        "evaluation_tools",
        "selection_tools",
        "decision_tools",
        "prioritization_tools",
        "voting_tools",
        "consensus_tools",
        "collaboration_platforms",
        "innovation_platforms",
        "idea_platforms",
        "crowdsourcing_platforms",
        "marketplace_platforms",
        "exchange_platforms",
        "trading_platforms",
        "auction_platforms",
        "bidding_platforms",
        "procurement_platforms",
        "sourcing_platforms",
        "supplier_platforms",
        "customer_platforms",
        "partner_platforms",
        "ecosystem_platforms",
        "api_platforms",
        "integration_hubs",
        "middleware_platforms",
        "messaging_platforms",
        "streaming_platforms",
        "event_platforms",
        "workflow_engines",
        "rules_engines",
        "decision_engines",
        "recommendation_engines",
        "search_engines",
        "matching_engines",
        "optimization_engines",
        "calculation_engines",
        "pricing_engines",
        "rating_engines",
        "scoring_engines",
        "ranking_engines",
        "classification_engines",
        "extraction_engines",
        "transformation_engines",
        "validation_engines",
        "verification_engines",
        "authentication_systems",
        "authorization_systems",
        "identity_systems",
        "access_systems",
        "privilege_systems",
        "role_systems",
        "policy_systems",
        "compliance_systems",
        "governance_systems",
        "risk_systems",
        "control_systems",
        "monitoring_systems",
        "alerting_systems",
        "notification_systems",
        "escalation_systems",
        "ticketing_systems",
        "tracking_systems",
        "routing_systems",
        "queuing_systems",
        "scheduling_systems",
        "booking_systems",
        "reservation_systems",
        "registration_systems",
        "enrollment_systems",
        "onboarding_systems",
        "provisioning_systems",
        "configuration_systems",
        "deployment_systems",
        "orchestration_systems",
        "automation_systems",
        "scripting_systems",
        "testing_systems",
        "validation_systems",
        "certification_systems",
        "accreditation_systems",
        "licensing_systems",
        "credentialing_systems",
        "privileging_systems",
        "appointment_systems",
        "assignment_systems",
        "allocation_systems",
        "distribution_systems",
        "routing_systems",
        "load_balancing_systems",
        "failover_systems",
        "recovery_systems",
        "backup_systems",
        "archive_systems",
        "retention_systems",
        "disposal_systems",
        "destruction_systems",
        "audit_systems",
        "logging_systems",
        "tracking_systems",
        "tracing_systems",
        "profiling_systems",
        "debugging_systems",
        "diagnostic_systems",
        "troubleshooting_systems",
        "support_systems",
        "help_systems",
        "knowledge_systems",
        "expert_systems",
        "advisory_systems",
        "recommendation_systems",
        "suggestion_systems",
        "feedback_systems",
        "rating_systems",
        "review_systems",
        "evaluation_systems",
        "assessment_systems",
        "measurement_systems",
        "metrics_systems",
        "analytics_systems",
        "reporting_systems",
        "dashboard_systems",
        "visualization_systems",
        "presentation_systems",
        "communication_systems",
        "collaboration_systems",
        "coordination_systems",
        "synchronization_systems",
        "integration_systems",
        "interface_systems",
        "gateway_systems",
        "proxy_systems",
        "cache_systems",
        "cdn_systems",
        "edge_systems",
        "distributed_systems",
        "cluster_systems",
        "grid_systems",
        "cloud_systems",
        "virtualization_systems",
        "container_systems",
        "orchestration_platforms",
        "management_platforms",
        "monitoring_platforms",
        "observability_platforms",
        "logging_platforms",
        "metrics_platforms",
        "tracing_platforms",
        "apm_platforms",
        "security_platforms",
        "compliance_platforms",
        "governance_platforms",
        "risk_platforms",
        "audit_platforms",
        "forensic_platforms",
        "investigation_platforms",
        "intelligence_platforms",
        "threat_platforms",
        "vulnerability_platforms",
        "patch_platforms",
        "update_platforms",
        "deployment_platforms",
        "release_platforms",
        "devops_platforms",
        "cicd_platforms",
        "testing_platforms",
        "quality_platforms",
        "performance_platforms",
        "load_testing_platforms",
        "stress_testing_platforms",
        "penetration_testing_platforms",
        "security_testing_platforms",
        "compliance_testing_platforms",
        "validation_platforms",
        "verification_platforms",
        "certification_platforms",
        "training_platforms",
        "learning_platforms",
        "education_platforms",
        "knowledge_platforms",
        "content_platforms",
        "media_platforms",
        "streaming_services",
        "broadcasting_systems",
        "distribution_networks",
        "delivery_systems",
        "fulfillment_systems",
        "logistics_systems",
        "transportation_systems",
        "routing_algorithms",
        "optimization_algorithms",
        "scheduling_algorithms",
        "planning_algorithms",
        "forecasting_algorithms",
        "prediction_algorithms",
        "machine_learning_algorithms",
        "deep_learning_algorithms",
        "neural_networks",
        "cognitive_systems",
        "ai_systems",
        "expert_systems",
        "decision_systems",
        "reasoning_systems",
        "inference_systems",
        "knowledge_graphs",
        "semantic_networks",
        "ontology_systems",
        "taxonomy_systems",
        "classification_systems",
        "categorization_systems",
        "tagging_systems",
        "metadata_systems",
        "catalog_systems",
        "registry_systems",
        "repository_systems",
        "library_systems",
        "archive_systems",
        "collection_systems",
        "curation_systems",
        "preservation_systems",
        "conservation_systems",
        "restoration_systems",
        "migration_systems",
        "transformation_systems",
        "conversion_systems",
        "translation_systems",
        "localization_systems",
        "internationalization_systems",
        "globalization_systems",
        "standardization_systems",
        "normalization_systems",
        "harmonization_systems",
        "synchronization_systems",
        "reconciliation_systems",
        "matching_systems",
        "deduplication_systems",
        "cleansing_systems",
        "enrichment_systems",
        "augmentation_systems",
        "enhancement_systems",
        "improvement_systems",
        "optimization_systems",
        "refinement_systems",
        "tuning_systems",
        "calibration_systems",
        "adjustment_systems",
        "correction_systems",
        "remediation_systems",
        "mitigation_systems",
        "prevention_systems",
        "protection_systems",
        "defense_systems",
        "security_systems",
        "safety_systems",
        "reliability_systems",
        "availability_systems",
        "resilience_systems",
        "redundancy_systems",
        "failover_systems",
        "disaster_recovery_systems",
        "business_continuity_systems",
        "crisis_management_systems",
        "emergency_response_systems",
        "incident_response_systems",
        "alert_systems",
        "warning_systems",
        "notification_systems",
        "communication_systems",
        "broadcast_systems",
        "announcement_systems",
        "messaging_systems",
        "chat_systems",
        "collaboration_systems",
        "conferencing_systems",
        "meeting_systems",
        "webinar_systems",
        "presentation_systems",
        "sharing_systems",
        "distribution_systems",
        "syndication_systems",
        "aggregation_systems",
        "federation_systems",
        "consolidation_systems",
        "integration_systems",
        "unification_systems",
        "centralization_systems",
        "standardization_systems",
        "normalization_systems",
        "canonical_systems",
        "master_data_systems",
        "reference_data_systems",
        "metadata_management",
        "data_governance",
        "data_quality",
        "data_lineage",
        "data_catalog",
        "data_dictionary",
        "business_glossary",
        "semantic_layer",
        "logical_models",
        "physical_models",
        "conceptual_models",
        "dimensional_models",
        "relational_models",
        "hierarchical_models",
        "network_models",
        "graph_models",
        "document_models",
        "key_value_models",
        "column_family_models",
        "time_series_models",
        "spatial_models",
        "temporal_models",
        "bitemporal_models",
        "multidimensional_models",
        "cube_models",
        "star_schemas",
        "snowflake_schemas",
        "fact_tables",
        "dimension_tables",
        "bridge_tables",
        "junction_tables",
        "lookup_tables",
        "reference_tables",
        "staging_tables",
        "temp_tables",
        "work_tables",
        "audit_tables",
        "history_tables",
        "archive_tables",
        "backup_tables",
        "recovery_tables",
        "replication_tables",
        "synchronization_tables",
        "queue_tables",
        "message_tables",
        "event_tables",
        "log_tables",
        "trace_tables",
        "metric_tables",
        "statistic_tables",
        "summary_tables",
        "aggregate_tables",
        "rollup_tables",
        "pivot_tables",
        "crosstab_tables",
        "report_tables",
        "export_tables",
        "import_tables",
        "interface_tables",
        "mapping_tables",
        "translation_tables",
        "conversion_tables",
        "validation_tables",
        "error_tables",
        "exception_tables",
        "rejection_tables",
        "quarantine_tables",
        "pending_tables",
        "processing_tables",
        "completed_tables",
        "result_tables",
        "output_tables",
        "delivery_tables",
        "distribution_tables",
        "notification_tables",
        "alert_tables",
        "escalation_tables",
        "workflow_tables",
        "task_tables",
        "assignment_tables",
        "schedule_tables",
        "calendar_tables",
        "event_tables",
        "reminder_tables",
        "tracking_tables",
        "status_tables",
        "progress_tables",
        "milestone_tables",
        "checkpoint_tables",
        "snapshot_tables",
        "version_tables",
        "release_tables",
        "deployment_tables",
        "configuration_tables",
        "parameter_tables",
        "setting_tables",
        "preference_tables",
        "option_tables",
        "feature_tables",
        "capability_tables",
        "permission_tables",
        "privilege_tables",
        "access_tables",
        "security_tables",
        "authentication_tables",
        "authorization_tables",
        "session_tables",
        "token_tables",
        "key_tables",
        "certificate_tables",
        "credential_tables",
        "identity_tables",
        "profile_tables",
        "account_tables",
        "user_tables",
        "group_tables",
        "role_tables",
        "organization_tables",
        "department_tables",
        "division_tables",
        "team_tables",
        "unit_tables",
        "location_tables",
        "facility_tables",
        "site_tables",
        "region_tables",
        "territory_tables",
        "zone_tables",
        "area_tables",
        "district_tables",
        "sector_tables",
        "segment_tables",
        "market_tables",
        "customer_tables",
        "client_tables",
        "patient_tables",
        "member_tables",
        "subscriber_tables",
        "beneficiary_tables",
        "dependent_tables",
        "contact_tables",
        "person_tables",
        "individual_tables",
        "entity_tables",
        "party_tables",
        "stakeholder_tables",
        "participant_tables",
        "actor_tables",
        "subject_tables",
        "object_tables",
        "resource_tables",
        "asset_tables",
        "item_tables",
        "product_tables",
        "service_tables",
        "offering_tables",
        "package_tables",
        "bundle_tables",
        "kit_tables",
        "set_tables",
        "collection_tables",
        "catalog_tables",
        "inventory_tables",
        "stock_tables",
        "supply_tables",
        "material_tables",
        "component_tables",
        "part_tables",
        "assembly_tables",
        "equipment_tables",
        "device_tables",
        "instrument_tables",
        "tool_tables",
        "machine_tables",
        "system_tables",
        "platform_tables",
        "infrastructure_tables",
        "network_tables",
        "server_tables",
        "storage_tables",
        "database_tables",
        "application_tables",
        "service_tables",
        "api_tables",
        "endpoint_tables",
        "interface_tables",
        "integration_tables",
        "connector_tables",
        "adapter_tables",
        "bridge_tables",
        "gateway_tables",
        "proxy_tables",
        "router_tables",
        "switch_tables",
        "hub_tables",
        "node_tables",
        "cluster_tables",
        "grid_tables",
        "mesh_tables",
        "topology_tables",
        "architecture_tables",
        "design_tables",
        "blueprint_tables",
        "template_tables",
        "pattern_tables",
        "model_tables",
        "schema_tables",
        "structure_tables",
        "format_tables",
        "layout_tables",
        "style_tables",
        "theme_tables",
        "skin_tables",
        "appearance_tables",
        "presentation_tables",
        "display_tables",
        "view_tables",
        "screen_tables",
        "page_tables",
        "form_tables",
        "field_tables",
        "control_tables",
        "widget_tables",
        "component_tables",
        "element_tables",
        "attribute_tables",
        "property_tables",
        "characteristic_tables",
        "feature_tables",
        "trait_tables",
        "quality_tables",
        "metric_tables",
        "measure_tables",
        "indicator_tables",
        "kpi_tables",
        "target_tables",
        "goal_tables",
        "objective_tables",
        "outcome_tables",
        "result_tables",
        "achievement_tables",
        "performance_tables",
        "score_tables",
        "rating_tables",
        "rank_tables",
        "grade_tables",
        "level_tables",
        "tier_tables",
        "class_tables",
        "category_tables",
        "type_tables",
        "kind_tables",
        "variety_tables",
        "variant_tables",
        "version_tables",
        "edition_tables",
        "release_tables",
        "build_tables",
        "patch_tables",
        "update_tables",
        "upgrade_tables",
        "migration_tables",
        "conversion_tables",
        "transformation_tables",
        "translation_tables",
        "mapping_tables",
        "crosswalk_tables",
        "concordance_tables",
        "equivalence_tables",
        "correspondence_tables",
        "relationship_tables",
        "association_tables",
        "link_tables",
        "connection_tables",
        "binding_tables",
        "coupling_tables",
        "dependency_tables",
        "reference_tables",
        "pointer_tables",
        "index_tables",
        "catalog_tables",
        "directory_tables",
        "registry_tables",
        "repository_tables",
        "store_tables",
        "warehouse_tables",
        "mart_tables",
        "hub_tables",
        "lake_tables",
        "pond_tables",
        "pool_tables",
        "cache_tables",
        "buffer_tables",
        "queue_tables",
        "stack_tables",
        "heap_tables",
        "list_tables",
        "array_tables",
        "vector_tables",
        "matrix_tables",
        "tensor_tables",
        "graph_tables",
        "tree_tables",
        "forest_tables",
        "network_tables",
        "mesh_tables",
        "web_tables",
        "cloud_tables",
        "fog_tables",
        "edge_tables",
        "node_tables",
        "vertex_tables",
        "edge_tables",
        "path_tables",
        "route_tables",
        "journey_tables",
        "trip_tables",
        "voyage_tables",
        "expedition_tables",
        "mission_tables",
        "campaign_tables",
        "program_tables",
        "project_tables",
        "initiative_tables",
        "effort_tables",
        "endeavor_tables",
        "undertaking_tables",
        "venture_tables",
        "enterprise_tables",
        "business_tables",
        "operation_tables",
        "activity_tables",
        "action_tables",
        "task_tables",
        "job_tables",
        "work_tables",
        "assignment_tables",
        "duty_tables",
        "responsibility_tables",
        "obligation_tables",
        "commitment_tables",
        "promise_tables",
        "agreement_tables",
        "contract_tables",
        "covenant_tables",
        "pact_tables",
        "treaty_tables",
        "alliance_tables",
        "partnership_tables",
        "collaboration_tables",
        "cooperation_tables",
        "coordination_tables",
        "synchronization_tables",
        "harmonization_tables",
        "alignment_tables",
        "integration_tables",
        "unification_tables",
        "consolidation_tables",
        "merger_tables",
        "acquisition_tables",
        "combination_tables",
        "fusion_tables",
        "blend_tables",
        "mixture_tables",
        "composite_tables",
        "compound_tables",
        "aggregate_tables",
        "collection_tables",
        "assembly_tables",
        "compilation_tables",
        "anthology_tables",
        "compendium_tables",
        "digest_tables",
        "summary_tables",
        "abstract_tables",
        "synopsis_tables",
        "outline_tables",
        "overview_tables",
        "preview_tables",
        "review_tables",
        "retrospective_tables",
        "analysis_tables",
        "study_tables",
        "research_tables",
        "investigation_tables",
        "examination_tables",
        "inspection_tables",
        "audit_tables",
        "assessment_tables",
        "evaluation_tables",
        "appraisal_tables",
        "valuation_tables",
        "estimation_tables",
        "calculation_tables",
        "computation_tables",
        "measurement_tables",
        "quantification_tables",
        "calibration_tables",
        "standardization_tables",
        "normalization_tables",
        "optimization_tables",
        "maximization_tables",
        "minimization_tables",
        "balancing_tables",
        "equilibrium_tables",
        "stability_tables",
        "steady_state_tables",
        "dynamic_tables",
        "transient_tables",
        "temporal_tables",
        "time_based_tables",
        "chronological_tables",
        "sequential_tables",
        "serial_tables",
        "parallel_tables",
        "concurrent_tables",
        "simultaneous_tables",
        "synchronous_tables",
        "asynchronous_tables",
        "real_time_tables",
        "near_real_time_tables",
        "batch_tables",
        "stream_tables",
        "flow_tables",
        "pipeline_tables",
        "channel_tables",
        "conduit_tables",
        "pathway_tables",
        "corridor_tables",
        "route_tables",
        "circuit_tables",
        "loop_tables",
        "cycle_tables",
        "iteration_tables",
        "recursion_tables",
        "repetition_tables",
        "recurrence_tables",
        "frequency_tables",
        "periodicity_tables",
        "rhythm_tables",
        "pattern_tables",
        "sequence_tables",
        "series_tables",
        "progression_tables",
        "evolution_tables",
        "development_tables",
        "growth_tables",
        "expansion_tables",
        "scaling_tables",
        "multiplication_tables",
        "division_tables",
        "distribution_tables",
        "allocation_tables",
        "apportionment_tables",
        "assignment_tables",
        "designation_tables",
        "nomination_tables",
        "appointment_tables",
        "selection_tables",
        "choice_tables",
        "option_tables",
        "alternative_tables",
        "variant_tables",
        "variation_tables",
        "deviation_tables",
        "divergence_tables",
        "difference_tables",
        "distinction_tables",
        "discrimination_tables",
        "differentiation_tables",
        "specialization_tables",
        "generalization_tables",
        "abstraction_tables",
        "concretization_tables",
        "instantiation_tables",
        "realization_tables",
        "implementation_tables",
        "execution_tables",
        "operation_tables",
        "function_tables",
        "procedure_tables",
        "process_tables",
        "method_tables",
        "technique_tables",
        "approach_tables",
        "strategy_tables",
        "tactic_tables",
        "plan_tables",
        "scheme_tables",
        "design_tables",
        "blueprint_tables",
        "architecture_tables",
        "framework_tables",
        "structure_tables",
        "organization_tables",
        "arrangement_tables",
        "configuration_tables",
        "setup_tables",
        "installation_tables",
        "deployment_tables",
        "rollout_tables",
        "launch_tables",
        "release_tables",
        "publication_tables",
        "distribution_tables",
        "dissemination_tables",
        "propagation_tables",
        "broadcast_tables",
        "transmission_tables",
        "communication_tables",
        "messaging_tables",
        "signaling_tables",
        "notification_tables",
        "alert_tables",
        "warning_tables",
        "alarm_tables",
        "reminder_tables",
        "prompt_tables",
        "cue_tables",
        "hint_tables",
        "suggestion_tables",
        "recommendation_tables",
        "advice_tables",
        "guidance_tables",
        "direction_tables",
        "instruction_tables",
        "command_tables",
        "order_tables",
        "directive_tables",
        "mandate_tables",
        "requirement_tables",
        "specification_tables",
        "standard_tables",
        "criterion_tables",
        "benchmark_tables",
        "baseline_tables",
        "threshold_tables",
        "limit_tables",
        "boundary_tables",
        "constraint_tables",
        "restriction_tables",
        "limitation_tables",
        "cap_tables",
        "ceiling_tables",
        "floor_tables",
        "range_tables",
        "scope_tables",
        "extent_tables",
        "coverage_tables",
        "span_tables",
        "reach_tables",
        "penetration_tables",
        "saturation_tables",
        "density_tables",
        "concentration_tables",
        "intensity_tables",
        "strength_tables",
        "power_tables",
        "force_tables",
        "energy_tables",
        "momentum_tables",
        "velocity_tables",
        "acceleration_tables",
        "speed_tables",
        "rate_tables",
        "pace_tables",
        "tempo_tables",
        "cadence_tables",
        "frequency_tables",
        "wavelength_tables",
        "amplitude_tables",
        "phase_tables",
        "angle_tables",
        "rotation_tables",
        "revolution_tables",
        "spin_tables",
        "turn_tables",
        "twist_tables",
        "bend_tables",
        "curve_tables",
        "arc_tables",
        "circle_tables",
        "sphere_tables",
        "globe_tables",
        "ball_tables",
        "orb_tables",
        "bubble_tables",
        "drop_tables",
        "particle_tables",
        "atom_tables",
        "molecule_tables",
        "compound_tables",
        "element_tables",
        "substance_tables",
        "material_tables",
        "matter_tables",
        "mass_tables",
        "weight_tables",
        "volume_tables",
        "density_tables",
        "pressure_tables",
        "temperature_tables",
        "heat_tables",
        "cold_tables",
        "climate_tables",
        "weather_tables",
        "season_tables",
        "month_tables",
        "week_tables",
        "day_tables",
        "hour_tables",
        "minute_tables",
        "second_tables",
        "millisecond_tables",
        "microsecond_tables",
        "nanosecond_tables",
        "picosecond_tables",
        "femtosecond_tables",
        "attosecond_tables",
        "zeptosecond_tables",
        "yoctosecond_tables",
        "planck_time_tables"
    ],
    
    "removed_columns": {
        # Columns that existed in original tables but are missing in new schema
        "profiles": [
            # List any columns that were in the original profiles/users table but not in new
        ],
        "tickets": [
            # Original staff_tickets had these columns not in new tickets table:
            "form_type",
            "location", 
            "assigned_to_email",
            "action_taken_at",
            "completed_by",
            "payload",
            "request_type_virtual"
        ],
    },
    
    "function_changes": [
        # Functions that were renamed or removed
        "handle_new_user() -> Not included in clean schema",
        "is_team_member() -> Not included", 
        "get_app_permission() -> Not included",
        "log_audit_event() -> Not included",
        "update_inventory_quantity() -> Not included",
        "Hundreds of other app-specific functions removed"
    ],
    
    "type_changes": {
        # ENUM or type changes
        "ticket_status": {
            "old": ['Pending Approval', 'Open', 'In Progress', 'Stalled', 'Approved', 'Denied', 'Completed'],
            "new": ['open', 'in-progress', 'resolved', 'closed']
        },
        "user_role": {
            "old": ['admin', 'staff', 'viewer'] + ['staff', 'manager', 'superadmin', ...],  # Multiple conflicting definitions
            "new": ['admin', 'staff', 'manager', 'superadmin', 'viewer']
        }
    }
}

def find_code_references(directory, changes):
    """Find all references to changed database objects in the codebase"""
    
    print("Database Schema Change Impact Analysis")
    print("=" * 50)
    print(f"Scanning directory: {directory}")
    print()
    
    # File extensions to scan
    extensions = ['.ts', '.tsx', '.js', '.jsx', '.sql', '.prisma']
    
    results = {
        "table_references": {},
        "column_references": {},
        "function_references": {},
        "type_references": {}
    }
    
    # Walk through all files
    for root, dirs, files in os.walk(directory):
        # Skip node_modules and .git
        dirs[:] = [d for d in dirs if d not in ['node_modules', '.git', '.next', 'dist', 'build']]
        
        for file in files:
            if any(file.endswith(ext) for ext in extensions):
                filepath = os.path.join(root, file)
                
                try:
                    with open(filepath, 'r', encoding='utf-8') as f:
                        content = f.read()
                        lines = content.split('\n')
                        
                        # Check for removed tables
                        for table in changes["removed_tables"]:
                            # Look for table references in queries, imports, types, etc.
                            patterns = [
                                f'from\\s+["\']?{table}["\']?',  # SQL FROM
                                f'join\\s+["\']?{table}["\']?',  # SQL JOIN
                                f'into\\s+["\']?{table}["\']?',  # SQL INSERT
                                f'update\\s+["\']?{table}["\']?', # SQL UPDATE
                                f'`{table}`',                     # Backtick references
                                f'"{table}"',                     # Quoted references
                                f"'{table}'",                     # Single quoted
                                f'\\.{table}\\b',                # Supabase client
                                f'<{table}>',                     # TypeScript generics
                                f'interface\\s+.*{table}',        # TypeScript interfaces
                                f'type\\s+.*{table}',            # TypeScript types
                            ]
                            
                            for i, line in enumerate(lines):
                                for pattern in patterns:
                                    if re.search(pattern, line, re.IGNORECASE):
                                        if table not in results["table_references"]:
                                            results["table_references"][table] = []
                                        results["table_references"][table].append({
                                            "file": filepath.replace(directory, ''),
                                            "line": i + 1,
                                            "content": line.strip()
                                        })
                                        break
                        
                        # Check for changed columns
                        for table, columns in changes["removed_columns"].items():
                            for column in columns:
                                patterns = [
                                    f'\\.{column}\\b',           # Object property access
                                    f'\\[[\'"]{column}[\'"]\\]', # Bracket notation
                                    f'{column}\\s*:',            # TypeScript types
                                    f'"{column}"',               # Quoted in SQL
                                    f"'{column}'",               # Single quoted
                                    f'`{column}`',               # Template literals
                                ]
                                
                                for i, line in enumerate(lines):
                                    for pattern in patterns:
                                        if re.search(pattern, line):
                                            key = f"{table}.{column}"
                                            if key not in results["column_references"]:
                                                results["column_references"][key] = []
                                            results["column_references"][key].append({
                                                "file": filepath.replace(directory, ''),
                                                "line": i + 1,
                                                "content": line.strip()
                                            })
                                            break
                        
                        # Check for renamed tables
                        for old_table, new_table in changes["table_renames"].items():
                            if old_table != new_table:  # Only if actually renamed
                                patterns = [
                                    f'\\b{old_table}\\b',
                                    f'["\']?{old_table}["\']?'
                                ]
                                
                                for i, line in enumerate(lines):
                                    for pattern in patterns:
                                        if re.search(pattern, line, re.IGNORECASE):
                                            key = f"{old_table} -> {new_table}"
                                            if key not in results["table_references"]:
                                                results["table_references"][key] = []
                                            results["table_references"][key].append({
                                                "file": filepath.replace(directory, ''),
                                                "line": i + 1,
                                                "content": line.strip()
                                            })
                                            break
                
                except Exception as e:
                    print(f"Error reading {filepath}: {e}")
    
    return results

def generate_report(results, changes):
    """Generate a detailed report of all changes needed"""
    
    print("\n" + "=" * 70)
    print("SCHEMA CHANGE IMPACT REPORT")
    print("=" * 70)
    
    # Summary
    total_issues = sum(len(refs) for refs in results["table_references"].values())
    total_issues += sum(len(refs) for refs in results["column_references"].values())
    
    print(f"\nTotal Issues Found: {total_issues}")
    print(f"Removed Tables: {len(changes['removed_tables'])}")
    print(f"Table Renames: {len(changes['table_renames'])}")
    print(f"Column Changes: {sum(len(cols) for cols in changes['removed_columns'].values())}")
    
    # Table References
    if results["table_references"]:
        print("\n" + "-" * 70)
        print("TABLE REFERENCES TO FIX")
        print("-" * 70)
        
        for table, refs in sorted(results["table_references"].items()):
            print(f"\n{table}: {len(refs)} references")
            for ref in refs[:5]:  # Show first 5
                print(f"  {ref['file']}:{ref['line']}")
                print(f"    {ref['content'][:100]}...")
            if len(refs) > 5:
                print(f"  ... and {len(refs) - 5} more")
    
    # Column References  
    if results["column_references"]:
        print("\n" + "-" * 70)
        print("COLUMN REFERENCES TO FIX")
        print("-" * 70)
        
        for column, refs in sorted(results["column_references"].items()):
            print(f"\n{column}: {len(refs)} references")
            for ref in refs[:5]:  # Show first 5
                print(f"  {ref['file']}:{ref['line']}")
                print(f"    {ref['content'][:100]}...")
            if len(refs) > 5:
                print(f"  ... and {len(refs) - 5} more")
    
    # Write detailed JSON report
    with open('schema-changes-report.json', 'w') as f:
        json.dump({
            "summary": {
                "total_issues": total_issues,
                "removed_tables": len(changes['removed_tables']),
                "table_renames": len(changes['table_renames']),
                "column_changes": sum(len(cols) for cols in changes['removed_columns'].values())
            },
            "changes": changes,
            "references": results
        }, f, indent=2)
    
    print(f"\nDetailed report saved to: schema-changes-report.json")
    
    # Migration hints
    print("\n" + "=" * 70)
    print("MIGRATION STRATEGY")
    print("=" * 70)
    print("""
1. For removed tables like 'staff_tickets' -> 'tickets':
   - Update all Supabase client calls
   - Update all SQL queries
   - Update all TypeScript interfaces
   
2. For changed columns:
   - Update form_data to contain what was in 'payload'
   - Map old status values to new ones
   - Update all property accesses

3. For reserved words like 'position':
   - Update all queries to use "position" (quoted)
   - Update all TypeScript interfaces

4. For missing business logic:
   - Re-add necessary functions and triggers
   - Consider using Supabase Edge Functions for complex logic
    """)

if __name__ == "__main__":
    import sys
    
    directory = sys.argv[1] if len(sys.argv) > 1 else "/q/Projects/ganger-platform"
    
    if not os.path.exists(directory):
        print(f"Directory not found: {directory}")
        sys.exit(1)
    
    results = find_code_references(directory, SCHEMA_CHANGES)
    generate_report(results, SCHEMA_CHANGES)