# Ganger Platform - External Domain Worker Configuration Template
#
# Template for patient/external access workers (handouts, kiosk, meds, reps)
# Each external domain gets its own specialized worker
#
# Performance Target: <20ms response time (no auth overhead)
# Bundle Size Target: <300KB (lighter than staff versions)

# TEMPLATE VARIABLES TO REPLACE:
# {APP_NAME} = handouts-patient, kiosk-patient, meds-patient, reps-booking
# {DOMAIN} = handouts, kiosk, meds, reps
# {DESCRIPTION} = Patient Handouts, Patient Kiosk, Patient Meds, Rep Booking

name = "ganger-{APP_NAME}"
main = "src/{APP_NAME}-worker.js"
compatibility_date = "2025-01-17"
compatibility_flags = ["nodejs_compat"]

# Observability for performance monitoring
[observability]
enabled = true
head_sampling_rate = 1

# Development environment
[env.development]
name = "ganger-{APP_NAME}-dev"
vars = { 
  ENVIRONMENT = "development",
  APP_TYPE = "external",
  APP_NAME = "{APP_NAME}",
  DEBUG_MODE = "true"
}

# Production environment
[env.production]
name = "ganger-{APP_NAME}"
route = "{DOMAIN}.gangerdermatology.com/*"
vars = { 
  ENVIRONMENT = "production",
  APP_TYPE = "external",
  APP_NAME = "{APP_NAME}",
  DEBUG_MODE = "false",
  # Working infrastructure values from /CLAUDE.md
  SUPABASE_URL = "https://pfqtzmxxxhhsxmlddrta.supabase.co"
}

# Security configuration (less restrictive for patients)
[[env.production.secrets]]
# Set via: wrangler secret put SUPABASE_ANON_KEY --env production

# Custom domain routing
[[env.production.routes]]
pattern = "{DOMAIN}.gangerdermatology.com/*"
zone_id = "ba76d3d3f41251c49f0365421bd644a5"

# Performance monitoring
[env.production.analytics_engine_datasets]
name = "{APP_NAME}_analytics"

# Resource limits (lighter for external access)
[limits]
cpu_ms = 30      # Faster for patient access
memory_mb = 32   # Smaller footprint for external apps

# Cache configuration for patient content
[env.production.vars]
CACHE_TTL = "300"  # 5 minutes for patient content
CORS_ENABLED = "true"
PATIENT_ACCESS = "true"

# EXAMPLE CONFIGURATIONS:

# For Patient Handouts (handouts.gangerdermatology.com):
# name = "ganger-handouts-patient"
# main = "src/handouts-patient-worker.js"
# route = "handouts.gangerdermatology.com/*"

# For Patient Kiosk (kiosk.gangerdermatology.com):
# name = "ganger-kiosk-patient" 
# main = "src/kiosk-patient-worker.js"
# route = "kiosk.gangerdermatology.com/*"

# For Patient Meds (meds.gangerdermatology.com):
# name = "ganger-meds-patient"
# main = "src/meds-patient-worker.js" 
# route = "meds.gangerdermatology.com/*"

# For Rep Booking (reps.gangerdermatology.com):
# name = "ganger-reps-booking"
# main = "src/reps-booking-worker.js"
# route = "reps.gangerdermatology.com/*"