# Ganger Platform - Staff Application Worker Configuration Template
#
# Template for staff application workers (16 specialized workers)
# Each staff app gets its own worker for optimal performance and scaling
#
# Performance Target: <25ms response time 
# Bundle Size Target: <500KB per worker

# TEMPLATE VARIABLES TO REPLACE:
# {APP_NAME} = inventory-staff, handouts-staff, kiosk-admin, etc.
# {APP_PATH} = inventory, handouts, kiosk, etc.
# {DESCRIPTION} = Inventory Management, Handouts Management, etc.

name = "ganger-{APP_NAME}"
main = "src/{APP_NAME}-worker.js"
compatibility_date = "2025-01-17"
compatibility_flags = ["nodejs_compat"]

# Static assets for Next.js applications
[assets]
directory = "./dist/"
binding = "ASSETS"
not_found_handling = "single-page-application"

# Observability for performance monitoring
[observability]
enabled = true
head_sampling_rate = 1

# Development environment
[env.development]
name = "ganger-{APP_NAME}-dev"
vars = { 
  ENVIRONMENT = "development",
  APP_TYPE = "staff",
  APP_NAME = "{APP_NAME}",
  APP_PATH = "{APP_PATH}",
  STAFF_PORTAL_URL = "http://localhost:3000",
  DEBUG_MODE = "true"
}

# Production environment
[env.production]
name = "ganger-{APP_NAME}"
vars = { 
  ENVIRONMENT = "production",
  APP_TYPE = "staff",
  APP_NAME = "{APP_NAME}",
  APP_PATH = "{APP_PATH}",
  STAFF_PORTAL_URL = "https://staff.gangerdermatology.com",
  DEBUG_MODE = "false",
  # Working infrastructure values from /CLAUDE.md
  SUPABASE_URL = "https://pfqtzmxxxhhsxmlddrta.supabase.co",
  GOOGLE_CLIENT_ID = "745912643942-ttm6166flfqbsad430k7a5q3n8stvv34.apps.googleusercontent.com",
  GOOGLE_DOMAIN = "gangerdermatology.com",
  CLOUDFLARE_ZONE_ID = "ba76d3d3f41251c49f0365421bd644a5"
}

# Security configuration (Google OAuth required)
[[env.production.secrets]]
# Set via: wrangler secret put SUPABASE_ANON_KEY --env production
# Set via: wrangler secret put SUPABASE_SERVICE_ROLE_KEY --env production  
# Set via: wrangler secret put GOOGLE_CLIENT_SECRET --env production

# Database connections
[[env.production.d1_databases]]
binding = "DB"
database_name = "ganger-platform-db"
database_id = "your-d1-database-id"

# Key-value storage for sessions
[[env.production.kv_namespaces]]
binding = "KV"
id = "your-kv-namespace-id"

# Performance monitoring
[env.production.analytics_engine_datasets]
name = "{APP_NAME}_analytics"

# Resource limits
[limits]
cpu_ms = 50      # Stay under Cloudflare limits
memory_mb = 64   # Optimized for individual apps

# Staff authentication requirements
[env.production.vars]
AUTH_REQUIRED = "true"
GOOGLE_AUTH_DOMAIN = "gangerdermatology.com"
SESSION_TIMEOUT = "86400"  # 24 hours
STAFF_ROLES = "admin,staff,viewer"

# EXAMPLE CONFIGURATIONS:

# For Inventory Management (/inventory):
# name = "ganger-inventory-staff"
# main = "src/inventory-staff-worker.js"
# APP_PATH = "inventory"

# For Handouts Management (/handouts):
# name = "ganger-handouts-staff"
# main = "src/handouts-staff-worker.js"
# APP_PATH = "handouts"

# For Kiosk Administration (/kiosk):
# name = "ganger-kiosk-admin"
# main = "src/kiosk-admin-worker.js"
# APP_PATH = "kiosk"

# For Medication Authorization (/meds):
# name = "ganger-meds-staff"
# main = "src/meds-staff-worker.js" 
# APP_PATH = "meds"

# For EOS L10 Management (/l10):
# name = "ganger-l10-staff"
# main = "src/l10-staff-worker.js"
# APP_PATH = "l10"

# For Rep Scheduling Admin (/reps):
# name = "ganger-reps-admin"
# main = "src/reps-admin-worker.js"
# APP_PATH = "reps"

# For Call Center Operations (/phones):
# name = "ganger-phones-staff"
# main = "src/phones-staff-worker.js"
# APP_PATH = "phones"

# For Batch Closeout (/batch):
# name = "ganger-batch-staff"
# main = "src/batch-staff-worker.js"
# APP_PATH = "batch"

# For Social Media Management (/socials):
# name = "ganger-socials-staff"
# main = "src/socials-staff-worker.js"
# APP_PATH = "socials"

# For Clinical Staffing (/staffing):
# name = "ganger-staffing-staff"
# main = "src/staffing-staff-worker.js"
# APP_PATH = "staffing"

# For Compliance Training (/compliance):
# name = "ganger-compliance-staff"
# main = "src/compliance-staff-worker.js"
# APP_PATH = "compliance"

# For Platform Dashboard (/dashboard):
# name = "ganger-dashboard-staff"
# main = "src/dashboard-staff-worker.js"
# APP_PATH = "dashboard"

# For Configuration Management (/config):
# name = "ganger-config-staff"
# main = "src/config-staff-worker.js"
# APP_PATH = "config"

# For Component Showcase (/showcase):
# name = "ganger-showcase-staff"
# main = "src/showcase-staff-worker.js"
# APP_PATH = "showcase"

# For Integration Status (/status):
# name = "ganger-status-staff"
# main = "src/status-staff-worker.js"
# APP_PATH = "status"