name = "ganger-integration-status"
main = "worker.js"  
compatibility_date = "2024-06-12"
compatibility_flags = ["nodejs_compat"]

[build]
# command = "npm run build command = "npm run build && npm run build:worker"command = "npm run build && npm run build:worker" npm run build:worker"

[env.production]
name = "ganger-integration-status-prod"
# Routes handled by staff-router.js at staff.gangerdermatology.com/status

[env.staging]
name = "ganger-integration-status-staging"

# R2 bucket for static assets
[[r2_buckets]]
binding = "ASSETS"
bucket_name = "ganger-integration-status-assets"
preview_bucket_name = "ganger-integration-status-assets-preview"

# Environment variables
[vars]
ENVIRONMENT = "production"
APP_NAME = "Integration Status"

# Secrets (set via wrangler secret put)
# NEXT_PUBLIC_SUPABASE_URL
# NEXT_PUBLIC_SUPABASE_ANON_KEY