# 🚀 Staff Portal Router - Dynamic Application Router
# Handles all staff.gangerdermatology.com traffic

name = "staff-portal-router"
main = "staff-router.js"
compatibility_date = "2024-11-01"
compatibility_flags = ["nodejs_compat"]

# 🌐 Custom Domain Routes
[[routes]]
pattern = "staff.gangerdermatology.com/*"
zone_name = "gangerdermatology.com"

# 🔒 Environment Variables
[env.production.vars]
ENVIRONMENT = "production"
PLATFORM_NAME = "Ganger Staff Portal Router"
SUPABASE_URL = "https://pfqtzmxxxhhsxmlddrta.supabase.co"
DOMAIN_BASE = "gangerdermatology.com"

# R2 Buckets for medical apps
[[env.production.r2_buckets]]
binding = "INVENTORY_BUCKET"
bucket_name = "inventory-management-production"

[[env.production.r2_buckets]]
binding = "HANDOUTS_BUCKET"
bucket_name = "handouts-production"

[[env.production.r2_buckets]]
binding = "MEDS_BUCKET"
bucket_name = "medication-auth-production"

[[env.production.r2_buckets]]
binding = "KIOSK_BUCKET"
bucket_name = "checkin-kiosk-production"
