name = "ganger-eos-l10-prod"
compatibility_date = "2024-12-13"
main = "worker.js"

[env.production]
name = "ganger-eos-l10-prod"

[env.staging]
name = "ganger-eos-l10-staging"

[env.production.vars]
ENVIRONMENT = "production"
APP_NAME = "eos-l10"