name = "ganger-inventory"
main = "worker-simple.js"
compatibility_date = "2024-06-12"
compatibility_flags = ["nodejs_compat"]

[env.production]
name = "ganger-inventory-prod"
# Routes handled by staff-router.js at staff.gangerdermatology.com/inventory

[env.staging]
name = "ganger-inventory-staging"

# Environment variables
[vars]
ENVIRONMENT = "production"
APP_NAME = "Inventory Management"