name = "inventory-management"
main = "worker.js"
compatibility_date = "2024-01-01"

[[r2_buckets]]
binding = "INVENTORY_BUCKET"
bucket_name = "inventory-management"
preview_bucket_name = "inventory-management-preview"

[env.production]
name = "inventory-management-production"
route = { pattern = "inventory.gangerdermatology.com/*", zone_id = "ba76d3d3f41251c49f0365421bd644a5" }

[[env.production.r2_buckets]]
binding = "INVENTORY_BUCKET"
bucket_name = "inventory-management-production"

[env.staging]
name = "inventory-management-staging"

[[env.staging.r2_buckets]]
binding = "INVENTORY_BUCKET"
bucket_name = "inventory-management-staging"