# =============================================================================
# GITHUB ENVIRONMENT CONFIGURATION - PRODUCTION
# =============================================================================
# Production environment configuration for Ganger Platform
# Auto-created via GitHub CLI or GitHub UI
# =============================================================================

name: production
url: https://staff.gangerdermatology.com

# Environment Protection Rules
protection_rules:
  # Require approval for production deployments
  required_reviewers: 
    - acganger  # Primary administrator
  
  # Only allow main branch and hotfix branches
  deployment_branch_policy:
    protected_branches: true
    custom_branches: ["main", "hotfix/*"]
  
  # Deployment restrictions
  wait_timer: 0  # No wait timer (approval is sufficient)
  prevent_self_review: false

# Environment Variables (non-sensitive)
variables:
  ENVIRONMENT_NAME: "production"
  DEPLOYMENT_TYPE: "production"
  DEBUG_MODE: "false"
  HEALTH_CHECK_INTERVAL: "60"
  
  # Application URLs
  NEXT_PUBLIC_STAFF_URL: "https://staff.gangerdermatology.com"
  NEXT_PUBLIC_INVENTORY_URL: "https://staff.gangerdermatology.com/inventory"
  NEXT_PUBLIC_HANDOUTS_URL: "https://staff.gangerdermatology.com/handouts"
  
  # Cloudflare Configuration
  CLOUDFLARE_ENVIRONMENT: "production"
  CLOUDFLARE_ZONE: "production"

# Required Secrets (configured in GitHub UI)
required_secrets:
  - CLOUDFLARE_API_TOKEN
  - CLOUDFLARE_ACCOUNT_ID
  - SUPABASE_URL
  - SUPABASE_ANON_KEY
  - SUPABASE_SERVICE_ROLE_KEY
  - SLACK_WEBHOOK_URL
  - STRIPE_PUBLISHABLE_KEY
  - STRIPE_SECRET_KEY
  - TWILIO_ACCOUNT_SID
  - TWILIO_AUTH_TOKEN

# Deployment Configuration
deployment_config:
  timeout_minutes: 45
  auto_deploy_on_push: false  # Require manual approval
  allowed_branches: ["main", "hotfix/*"]
  deployment_strategy: "blue_green"
  rollback_enabled: true
  
# Monitoring Configuration
monitoring:
  health_check_enabled: true
  health_check_timeout: 120
  health_check_retries: 5
  status_page_enabled: true
  uptime_monitoring: true
  performance_monitoring: true

# Notification Configuration
notifications:
  slack_enabled: true
  email_enabled: true
  webhook_enabled: true
  pagerduty_enabled: false

# Security Configuration
security:
  hipaa_compliance: true
  audit_logging: true
  access_logging: true
  encryption_at_rest: true
  encryption_in_transit: true

# Backup Configuration
backup:
  automated_backup: true
  backup_frequency: "daily"
  retention_period: "30_days"
  cross_region_backup: true

---
# GitHub CLI Commands to Create Environment
# Run these commands to set up the production environment:

# gh api repos/acganger/ganger-platform/environments/production --method PUT \
#   --field "deployment_branch_policy[protected_branches]=true" \
#   --field "protection_rules[0][type]=required_reviewers" \
#   --field "protection_rules[0][required_reviewers][0][login]=acganger"

# Add required secrets:
# gh secret set CLOUDFLARE_API_TOKEN --env production --body "$CLOUDFLARE_API_TOKEN"
# gh secret set CLOUDFLARE_ACCOUNT_ID --env production --body "$CLOUDFLARE_ACCOUNT_ID"
# gh secret set SUPABASE_URL --env production --body "$SUPABASE_URL"
# gh secret set SUPABASE_ANON_KEY --env production --body "$SUPABASE_ANON_KEY"
# gh secret set SUPABASE_SERVICE_ROLE_KEY --env production --body "$SUPABASE_SERVICE_ROLE_KEY"
# gh secret set SLACK_WEBHOOK_URL --env production --body "$SLACK_WEBHOOK_URL"
# gh secret set STRIPE_PUBLISHABLE_KEY --env production --body "$STRIPE_PUBLISHABLE_KEY"
# gh secret set STRIPE_SECRET_KEY --env production --body "$STRIPE_SECRET_KEY"
# gh secret set TWILIO_ACCOUNT_SID --env production --body "$TWILIO_ACCOUNT_SID"
# gh secret set TWILIO_AUTH_TOKEN --env production --body "$TWILIO_AUTH_TOKEN"