name = "ganger-handouts"
main = "worker-simple.js"
compatibility_date = "2024-06-12"
compatibility_flags = ["nodejs_compat"]

[env.production]
name = "ganger-handouts-prod"
# Routes handled by staff-router.js at staff.gangerdermatology.com/handouts

[env.staging]
name = "ganger-handouts-staging"

# Environment variables
[vars]
ENVIRONMENT = "production"
APP_NAME = "Patient Handouts"