name = "ganger-handouts-staff"
main = ".vercel/output/static/_worker.js/index.js"
compatibility_date = "2025-01-18"
compatibility_flags = ["nodejs_compat"]

# Staff Access - Full admin capabilities
# Google OAuth authentication required
# Focus on creation, editing, distribution management

build.command = "npm run build && npx @cloudflare/next-on-pages"

[assets]
directory = ".vercel/output/static"
binding = "ASSETS"
not_found_handling = "single-page-application"

[[r2_buckets]]
binding = "HANDOUTS_BUCKET"
bucket_name = "ganger-handouts-assets"

[observability]
enabled = true
head_sampling_rate = 1

[vars]
ENVIRONMENT = "production"
APP_NAME = "handouts-staff"
APP_VERSION = "1.0.0"
ACCESS_TYPE = "staff"

[env.production]
name = "ganger-handouts-staff"

# Note: Staff routing handled by platform worker at staff.gangerdermatology.com/handouts

[[env.production.r2_buckets]]
binding = "HANDOUTS_BUCKET"
bucket_name = "ganger-handouts-assets"