name = "ganger-handouts-patient"
main = ".vercel/output/static/_worker.js/index.js"
compatibility_date = "2025-01-18"
compatibility_flags = ["nodejs_compat"]

# Patient Access - Limited to viewing/downloading handouts
# No authentication required
# Focus on QR code scanning, PDF access

build.command = "npm run build && npx @cloudflare/next-on-pages"

[assets]
directory = ".vercel/output/static"
binding = "ASSETS"
not_found_handling = "single-page-application"

[[r2_buckets]]
binding = "HANDOUTS_BUCKET"
bucket_name = "ganger-handouts-assets"

[observability]
enabled = true
head_sampling_rate = 1

[vars]
ENVIRONMENT = "production"
APP_NAME = "handouts-patient"
APP_VERSION = "1.0.0"
ACCESS_TYPE = "patient"

[env.production]
name = "ganger-handouts-patient"

[[env.production.routes]]
pattern = "handouts.gangerdermatology.com/*"
zone_id = "ba76d3d3f41251c49f0365421bd644a5"

[[env.production.r2_buckets]]
binding = "HANDOUTS_BUCKET"
bucket_name = "ganger-handouts-assets"