name = "pharma-scheduling"
main = "worker.js"
compatibility_date = "2024-01-01"

[[r2_buckets]]
binding = "PHARMA_SCHEDULING_BUCKET"
bucket_name = "pharma-scheduling"
preview_bucket_name = "pharma-scheduling-preview"

[env.production]
name = "pharma-scheduling-production"
route = { pattern = "pharma.gangerdermatology.com/*", zone_id = "ba76d3d3f41251c49f0365421bd644a5" }

[[env.production.r2_buckets]]
binding = "PHARMA_SCHEDULING_BUCKET"
bucket_name = "pharma-scheduling-production"

[env.staging]
name = "pharma-scheduling-staging"

[[env.staging.r2_buckets]]
binding = "PHARMA_SCHEDULING_BUCKET"
bucket_name = "pharma-scheduling-staging"