name = "ganger-reps-staff"
main = ".vercel/output/static/_worker.js/index.js"
compatibility_date = "2025-01-18"
compatibility_flags = ["nodejs_compat"]

build.command = "npm run build && pnpm exec next-on-pages"

[assets]
directory = ".vercel/output/static"
binding = "ASSETS"
not_found_handling = "single-page-application"

[[r2_buckets]]
binding = "PHARMA_SCHEDULING_BUCKET"
bucket_name = "pharma-scheduling-staff"
preview_bucket_name = "pharma-scheduling-staff-preview"

[env.production]
name = "ganger-reps-staff"
routes = [
  { pattern = "staff.gangerdermatology.com/reps", zone_id = "ba76d3d3f41251c49f0365421bd644a5" },
  { pattern = "staff.gangerdermatology.com/reps/*", zone_id = "ba76d3d3f41251c49f0365421bd644a5" }
]

[[env.production.r2_buckets]]
binding = "PHARMA_SCHEDULING_BUCKET"
bucket_name = "pharma-scheduling-staff-production"

[env.staging]
name = "ganger-reps-staff-staging"

[[env.staging.r2_buckets]]
binding = "PHARMA_SCHEDULING_BUCKET"
bucket_name = "pharma-scheduling-staff-staging"