name: 🚀 Deploy Platform Worker

on:
  push:
    branches: [ main ]
    paths: [ 'cloudflare-workers/**' ]
  workflow_dispatch:

env:
  NODE_VERSION: '20'
  PNPM_VERSION: '8'

jobs:
  deploy-platform-worker:
    name: Deploy Platform Worker
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          run_install: false

      - name: Deploy Platform Worker
        run: |
          cd cloudflare-workers
          npx wrangler deploy --env production
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}

      - name: Deployment Success
        run: |
          echo "✅ Platform Worker deployed successfully!"
          echo "🌐 Handles: staff.gangerdermatology.com, reps.gangerdermatology.com, kiosk.gangerdermatology.com"
          echo "🔄 Routing: Path-based routing for all staff applications"