name = "ganger-inventory-prod"
compatibility_date = "2024-12-13"
main = "worker.js"

[env.production]
name = "ganger-inventory-production"
account_id = "68d0160c9915efebbbecfddfd48cddab"

# R2 bucket for static assets
[[env.production.r2_buckets]]
binding = "STATIC_ASSETS"
bucket_name = "ganger-inventory-assets"
preview_bucket_name = "ganger-inventory-assets"

[env.production.vars]
ENVIRONMENT = "production"
APP_NAME = "inventory"