name = "ganger-socials-reviews"
main = "worker-simple.js"
compatibility_date = "2024-06-12"
compatibility_flags = ["nodejs_compat"]

[env.production]
name = "ganger-socials-reviews-prod"
# Routes handled by staff-router.js at staff.gangerdermatology.com/socials-reviews

[env.staging]
name = "ganger-socials-reviews-staging"

# Environment variables
[vars]
ENVIRONMENT = "production"
APP_NAME = "Socials and Reviews Management"