name = "socials-reviews"
main = "worker.js"
compatibility_date = "2024-01-01"

[[r2_buckets]]
binding = "SOCIALS_REVIEWS_BUCKET"
bucket_name = "socials-reviews"
preview_bucket_name = "socials-reviews-preview"

[env.production]
name = "socials-reviews-production"
route = { pattern = "socials.gangerdermatology.com/*", zone_id = "ba76d3d3f41251c49f0365421bd644a5" }

[[env.production.r2_buckets]]
binding = "SOCIALS_REVIEWS_BUCKET"
bucket_name = "socials-reviews-production"

[env.staging]
name = "socials-reviews-staging"

[[env.staging.r2_buckets]]
binding = "SOCIALS_REVIEWS_BUCKET"
bucket_name = "socials-reviews-staging"