name = "ganger-eos-l10-prod"
compatibility_date = "2024-12-13"
main = "worker.js"

# Static assets from Next.js build
[site]
bucket = "../../apps/eos-l10/.next/static"

[env.production]
name = "ganger-eos-l10-prod"

[env.staging]
name = "ganger-eos-l10-staging"

# Environment variables
[vars]
ENVIRONMENT = "production"
APP_NAME = "eos-l10"

# Supabase configuration (configure in Cloudflare dashboard for security)
# SUPABASE_URL = "https://pfqtzmxxxhhsxmlddrta.supabase.co"
# SUPABASE_ANON_KEY = "..."
# GOOGLE_CLIENT_ID = "..."