// Common error codes
export const ErrorCodes = {
    // Authentication
    UNAUTHORIZED: 'UNAUTHORIZED',
    INSUFFICIENT_PERMISSIONS: 'INSUFFICIENT_PERMISSIONS',
    INVALID_TOKEN: 'INVALID_TOKEN',
    // Validation
    VALIDATION_ERROR: 'VALIDATION_ERROR',
    INVALID_REQUEST: 'INVALID_REQUEST',
    MISSING_REQUIRED_FIELD: 'MISSING_REQUIRED_FIELD',
    // Resources
    RESOURCE_NOT_FOUND: 'RESOURCE_NOT_FOUND',
    RESOURCE_ALREADY_EXISTS: 'RESOURCE_ALREADY_EXISTS',
    // External Services
    EXTERNAL_SERVICE_ERROR: 'EXTERNAL_SERVICE_ERROR',
    SYNC_FAILED: 'SYNC_FAILED',
    // Rate Limiting
    RATE_LIMIT_EXCEEDED: 'RATE_LIMIT_EXCEEDED',
    // Generic
    INTERNAL_ERROR: 'INTERNAL_ERROR',
    METHOD_NOT_ALLOWED: 'METHOD_NOT_ALLOWED',
    DATABASE_ERROR: 'DATABASE_ERROR'
};
// Export AI Purchasing types
export * from './ai-purchasing';
