name = "component-showcase"
main = "worker.js"
compatibility_date = "2024-01-01"

[[r2_buckets]]
binding = "COMPONENT_SHOWCASE_BUCKET"
bucket_name = "component-showcase"
preview_bucket_name = "component-showcase-preview"

[env.production]
name = "component-showcase-production"
route = { pattern = "showcase.gangerdermatology.com/*", zone_id = "ba76d3d3f41251c49f0365421bd644a5" }

[[env.production.r2_buckets]]
binding = "COMPONENT_SHOWCASE_BUCKET"
bucket_name = "component-showcase-production"

[env.staging]
name = "component-showcase-staging"

[[env.staging.r2_buckets]]
binding = "COMPONENT_SHOWCASE_BUCKET"
bucket_name = "component-showcase-staging"