name = "ganger-clinical-staffing-v2"
main = "worker.js"
compatibility_date = "2024-01-01"

[[r2_buckets]]
binding = "CLINICAL_STAFFING_BUCKET"
bucket_name = "ganger-clinical-staffing"
preview_bucket_name = "ganger-clinical-staffing-preview"

[env.production]
name = "ganger-clinical-staffing-v2"

[[env.production.r2_buckets]]
binding = "CLINICAL_STAFFING_BUCKET"
bucket_name = "ganger-clinical-staffing-production"

[env.staging]
name = "ganger-clinical-staffing-staging"

[[env.staging.r2_buckets]]
binding = "CLINICAL_STAFFING_BUCKET"
bucket_name = "ganger-clinical-staffing-staging"