name = "ganger-kiosk-admin"
main = ".vercel/output/static/_worker.js/index.js"
compatibility_date = "2025-01-18"
compatibility_flags = ["nodejs_compat"]

# Staff Interface - Monitoring dashboard
# Session management, troubleshooting, kiosk administration
# Requires Google OAuth authentication

build.command = "npm run build && npx @cloudflare/next-on-pages"

[assets]
directory = ".vercel/output/static"
binding = "ASSETS"
not_found_handling = "single-page-application"

[[r2_buckets]]
binding = "CHECKIN_KIOSK_BUCKET"
bucket_name = "ganger-checkin-kiosk-production"

[observability]
enabled = true
head_sampling_rate = 1

[vars]
ENVIRONMENT = "production"
APP_NAME = "checkin-kiosk-admin"
APP_VERSION = "1.0.0"
INTERFACE_TYPE = "staff-monitoring"

[env.production]
name = "ganger-kiosk-admin"

# Note: Staff routing handled by platform worker at staff.gangerdermatology.com/kiosk

[[env.production.r2_buckets]]
binding = "CHECKIN_KIOSK_BUCKET"
bucket_name = "ganger-checkin-kiosk-production"