#!/bin/bash

echo "🧪 Testing Gateway Architecture with Staff Portal"
echo "=============================================="
echo ""
echo "This script will guide you through testing the new gateway architecture"
echo ""

echo "📋 Pre-deployment Checklist:"
echo "✅ 1. Staff app middleware.ts created"
echo "✅ 2. vercel.json rewrites removed"
echo "✅ 3. @vercel/edge-config dependency added"
echo "✅ 4. googleapis dependency removed"
echo "✅ 5. All apps have basePath configured"
echo "✅ 6. SSO cookie domain configuration added"
echo ""

echo "🔧 Manual Steps Required:"
echo ""
echo "1. Create Edge Config in Vercel Dashboard:"
echo "   - Go to: https://vercel.com/team_wpY7PcIsYQNnslNN39o7fWvS/stores"
echo "   - Create store named: 'ganger-platform-app-urls'"
echo "   - Copy the JSON from scripts/setup-edge-config.sh"
echo "   - Get the connection string"
echo ""

echo "2. Add Edge Config to Staff App Environment:"
echo "   - Go to: Staff app settings in Vercel"
echo "   - Add: EDGE_CONFIG=<connection-string>"
echo ""

echo "3. Deploy Staff Portal:"
echo "   cd apps/staff"
echo "   git add ."
echo "   git commit -m 'feat: implement gateway architecture with Edge Config'"
echo "   git push origin main"
echo ""

echo "4. Test One App (e.g., inventory):"
echo "   - Deploy inventory app"
echo "   - Update Edge Config with new inventory URL"
echo "   - Test access via: staff.gangerdermatology.com/inventory"
echo ""

echo "🧪 Testing Checklist:"
echo "[ ] Staff portal loads at staff.gangerdermatology.com"
echo "[ ] Edge Config is read successfully (check logs)"
echo "[ ] Navigating to /inventory proxies correctly"
echo "[ ] SSO cookie persists across navigation"
echo "[ ] No CORS or cookie domain errors"
echo ""

echo "📝 If Successful:"
echo "1. Update all app URLs in Edge Config"
echo "2. Deploy remaining apps with basePath"
echo "3. Update documentation"
echo ""

echo "🔧 Rollback Plan:"
echo "If issues occur, revert by:"
echo "1. Re-adding rewrites to vercel.json"
echo "2. Removing middleware.ts"
echo "3. Deploying staff app again"