name = "ganger-staff-router-prod"
compatibility_date = "2024-12-13"
main = "worker.js"

[env.production]
name = "ganger-staff-router-prod"
routes = [
  { pattern = "staff.gangerdermatology.com/*", zone_id = "ba76d3d3f41251c49f0365421bd644a5" }
]
[env.production.vars]
ENVIRONMENT = "production"

[env.staging]
name = "ganger-staff-router-staging"
[env.staging.vars]
ENVIRONMENT = "staging"