name = "ganger-meds-staff"
main = ".vercel/output/static/_worker.js/index.js"
compatibility_date = "2025-01-18"
compatibility_flags = ["nodejs_compat"]

# Staff access to medication authorization management
# Requires Google OAuth authentication
# Full admin capabilities: review, AI assistance, approval workflow

build.command = "npm run build && pnpm exec next-on-pages"

[assets]
directory = ".vercel/output/static"
binding = "ASSETS"
not_found_handling = "single-page-application"

[observability]
enabled = true
head_sampling_rate = 1

[env.production]
name = "ganger-meds-staff"

# Note: Staff routing handled by platform worker at staff.gangerdermatology.com/meds