name = "ganger-medication-auth"
main = "worker.js"
compatibility_date = "2024-06-12"
compatibility_flags = ["nodejs_compat"]

# Build is handled in CI/CD pipeline
# [build]
# command = "npm run build && npm run build:worker"

[env.production]
name = "ganger-medication-auth-prod"
routes = [
  { pattern = "meds.gangerdermatology.com/*", zone_name = "gangerdermatology.com" }
]

[env.staging]
name = "ganger-medication-auth-staging"

# R2 bucket for static assets
[[r2_buckets]]
binding = "ASSETS"
bucket_name = "ganger-medication-auth-assets"
preview_bucket_name = "ganger-medication-auth-assets-preview"

# Environment variables
[vars]
ENVIRONMENT = "production"
APP_NAME = "Medication Authorization"

# Secrets (set via wrangler secret put)
# NEXT_PUBLIC_SUPABASE_URL
# NEXT_PUBLIC_SUPABASE_ANON_KEY