name = "ganger-meds-patient"
main = ".vercel/output/static/_worker.js/index.js"
compatibility_date = "2025-01-18"
compatibility_flags = ["nodejs_compat"]

# Patient access to medication authorization portal
# Public access for prior auth requests, status tracking, document upload

build.command = "npm run build && pnpm exec next-on-pages"

[assets]
directory = ".vercel/output/static"
binding = "ASSETS"
not_found_handling = "single-page-application"

[observability]
enabled = true
head_sampling_rate = 1

[env.production]
name = "ganger-meds-patient"

[[env.production.routes]]
pattern = "meds.gangerdermatology.com/*"
zone_id = "ba76d3d3f41251c49f0365421bd644a5"