// types/database.ts
export interface Database {
  public: {
    Tables: {
      integrations: {
        Row: {
          id: string;
          name: string;
          display_name: string;
          description: string | null;
          service_type: string;
          category: string;
          base_url: string | null;
          health_check_endpoint: string | null;
          auth_type: string;
          auth_config: any | null;
          is_active: boolean;
          is_critical: boolean;
          monitoring_enabled: boolean;
          health_check_interval_minutes: number;
          timeout_seconds: number;
          current_health_status: 'healthy' | 'warning' | 'critical' | 'unknown';
          last_health_check: string | null;
          last_successful_check: string | null;
          consecutive_failures: number;
          icon_url: string | null;
          documentation_url: string | null;
          responsible_team: string | null;
          environment: 'development' | 'staging' | 'production';
          version: string | null;
          custom_headers: any | null;
          expected_response_codes: number[];
          health_check_method: string;
          health_check_body: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          display_name: string;
          description?: string | null;
          service_type: string;
          category?: string;
          base_url?: string | null;
          health_check_endpoint?: string | null;
          auth_type: string;
          auth_config?: any | null;
          is_active?: boolean;
          is_critical?: boolean;
          monitoring_enabled?: boolean;
          health_check_interval_minutes?: number;
          timeout_seconds?: number;
          current_health_status?: 'healthy' | 'warning' | 'critical' | 'unknown';
          last_health_check?: string | null;
          last_successful_check?: string | null;
          consecutive_failures?: number;
          icon_url?: string | null;
          documentation_url?: string | null;
          responsible_team?: string | null;
          environment?: 'development' | 'staging' | 'production';
          version?: string | null;
          custom_headers?: any | null;
          expected_response_codes?: number[];
          health_check_method?: string;
          health_check_body?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          name?: string;
          display_name?: string;
          description?: string | null;
          service_type?: string;
          category?: string;
          base_url?: string | null;
          health_check_endpoint?: string | null;
          auth_type?: string;
          auth_config?: any | null;
          is_active?: boolean;
          is_critical?: boolean;
          monitoring_enabled?: boolean;
          health_check_interval_minutes?: number;
          timeout_seconds?: number;
          current_health_status?: 'healthy' | 'warning' | 'critical' | 'unknown';
          last_health_check?: string | null;
          last_successful_check?: string | null;
          consecutive_failures?: number;
          icon_url?: string | null;
          documentation_url?: string | null;
          responsible_team?: string | null;
          environment?: 'development' | 'staging' | 'production';
          version?: string | null;
          custom_headers?: any | null;
          expected_response_codes?: number[];
          health_check_method?: string;
          health_check_body?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      integration_health_checks: {
        Row: {
          id: string;
          integration_id: string;
          check_timestamp: string;
          response_time_ms: number | null;
          status_code: number | null;
          response_body: string | null;
          error_message: string | null;
          is_successful: boolean;
          health_status: 'healthy' | 'warning' | 'critical' | 'unknown';
          check_type: string;
          triggered_by: string | null;
          dns_resolution_time_ms: number | null;
          tcp_connection_time_ms: number | null;
          ssl_handshake_time_ms: number | null;
          availability_score: number | null;
          performance_score: number | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          integration_id: string;
          check_timestamp?: string;
          response_time_ms?: number | null;
          status_code?: number | null;
          response_body?: string | null;
          error_message?: string | null;
          is_successful: boolean;
          health_status: 'healthy' | 'warning' | 'critical' | 'unknown';
          check_type?: string;
          triggered_by?: string | null;
          dns_resolution_time_ms?: number | null;
          tcp_connection_time_ms?: number | null;
          ssl_handshake_time_ms?: number | null;
          availability_score?: number | null;
          performance_score?: number | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          integration_id?: string;
          check_timestamp?: string;
          response_time_ms?: number | null;
          status_code?: number | null;
          response_body?: string | null;
          error_message?: string | null;
          is_successful?: boolean;
          health_status?: 'healthy' | 'warning' | 'critical' | 'unknown';
          check_type?: string;
          triggered_by?: string | null;
          dns_resolution_time_ms?: number | null;
          tcp_connection_time_ms?: number | null;
          ssl_handshake_time_ms?: number | null;
          availability_score?: number | null;
          performance_score?: number | null;
          created_at?: string;
        };
      };
      integration_metrics: {
        Row: {
          id: string;
          integration_id: string;
          metric_date: string;
          metric_hour: number | null;
          time_window_minutes: number;
          total_checks: number;
          successful_checks: number;
          failed_checks: number;
          uptime_percentage: number | null;
          avg_response_time_ms: number | null;
          min_response_time_ms: number | null;
          max_response_time_ms: number | null;
          p50_response_time_ms: number | null;
          p95_response_time_ms: number | null;
          p99_response_time_ms: number | null;
          error_count: number;
          error_rate: number | null;
          status_2xx_count: number;
          status_3xx_count: number;
          status_4xx_count: number;
          status_5xx_count: number;
          timeout_count: number;
          availability_score: number | null;
          performance_score: number | null;
          reliability_score: number | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          integration_id: string;
          metric_date: string;
          metric_hour?: number | null;
          time_window_minutes?: number;
          total_checks?: number;
          successful_checks?: number;
          failed_checks?: number;
          avg_response_time_ms?: number | null;
          min_response_time_ms?: number | null;
          max_response_time_ms?: number | null;
          p50_response_time_ms?: number | null;
          p95_response_time_ms?: number | null;
          p99_response_time_ms?: number | null;
          error_count?: number;
          status_2xx_count?: number;
          status_3xx_count?: number;
          status_4xx_count?: number;
          status_5xx_count?: number;
          timeout_count?: number;
          availability_score?: number | null;
          performance_score?: number | null;
          reliability_score?: number | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          integration_id?: string;
          metric_date?: string;
          metric_hour?: number | null;
          time_window_minutes?: number;
          total_checks?: number;
          successful_checks?: number;
          failed_checks?: number;
          avg_response_time_ms?: number | null;
          min_response_time_ms?: number | null;
          max_response_time_ms?: number | null;
          p50_response_time_ms?: number | null;
          p95_response_time_ms?: number | null;
          p99_response_time_ms?: number | null;
          error_count?: number;
          status_2xx_count?: number;
          status_3xx_count?: number;
          status_4xx_count?: number;
          status_5xx_count?: number;
          timeout_count?: number;
          availability_score?: number | null;
          performance_score?: number | null;
          reliability_score?: number | null;
          created_at?: string;
        };
      };
      alert_rules: {
        Row: {
          id: string;
          integration_id: string | null;
          rule_name: string;
          rule_description: string | null;
          alert_type: string;
          condition_metric: string;
          condition_operator: string;
          condition_threshold: number;
          condition_duration_minutes: number;
          severity: 'info' | 'warning' | 'critical' | 'urgent';
          auto_resolve: boolean;
          cooldown_minutes: number;
          notification_channels: string[];
          notification_recipients: string[];
          escalation_enabled: boolean;
          escalation_after_minutes: number;
          escalation_recipients: string[];
          is_active: boolean;
          last_triggered: string | null;
          trigger_count: number;
          business_hours_only: boolean;
          business_hours_start: string;
          business_hours_end: string;
          business_days: number[];
          created_by: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          integration_id?: string | null;
          rule_name: string;
          rule_description?: string | null;
          alert_type: string;
          condition_metric: string;
          condition_operator: string;
          condition_threshold: number;
          condition_duration_minutes?: number;
          severity: 'info' | 'warning' | 'critical' | 'urgent';
          auto_resolve?: boolean;
          cooldown_minutes?: number;
          notification_channels?: string[];
          notification_recipients?: string[];
          escalation_enabled?: boolean;
          escalation_after_minutes?: number;
          escalation_recipients?: string[];
          is_active?: boolean;
          last_triggered?: string | null;
          trigger_count?: number;
          business_hours_only?: boolean;
          business_hours_start?: string;
          business_hours_end?: string;
          business_days?: number[];
          created_by?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          integration_id?: string | null;
          rule_name?: string;
          rule_description?: string | null;
          alert_type?: string;
          condition_metric?: string;
          condition_operator?: string;
          condition_threshold?: number;
          condition_duration_minutes?: number;
          severity?: 'info' | 'warning' | 'critical' | 'urgent';
          auto_resolve?: boolean;
          cooldown_minutes?: number;
          notification_channels?: string[];
          notification_recipients?: string[];
          escalation_enabled?: boolean;
          escalation_after_minutes?: number;
          escalation_recipients?: string[];
          is_active?: boolean;
          last_triggered?: string | null;
          trigger_count?: number;
          business_hours_only?: boolean;
          business_hours_start?: string;
          business_hours_end?: string;
          business_days?: number[];
          created_by?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      alert_incidents: {
        Row: {
          id: string;
          alert_rule_id: string;
          integration_id: string;
          triggered_at: string;
          resolved_at: string | null;
          duration_minutes: number | null;
          alert_message: string;
          severity: string;
          trigger_value: number | null;
          threshold_value: number | null;
          status: 'open' | 'acknowledged' | 'resolved' | 'suppressed';
          acknowledged_by: string | null;
          acknowledged_at: string | null;
          resolved_by: string | null;
          resolution_note: string | null;
          affected_services: string[] | null;
          business_impact: 'none' | 'low' | 'medium' | 'high' | 'critical' | null;
          estimated_affected_users: number | null;
          escalation_level: number;
          escalated_at: string | null;
          escalated_to: string[] | null;
          notifications_sent: any | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          alert_rule_id: string;
          integration_id: string;
          triggered_at?: string;
          resolved_at?: string | null;
          duration_minutes?: number | null;
          alert_message: string;
          severity: string;
          trigger_value?: number | null;
          threshold_value?: number | null;
          status?: 'open' | 'acknowledged' | 'resolved' | 'suppressed';
          acknowledged_by?: string | null;
          acknowledged_at?: string | null;
          resolved_by?: string | null;
          resolution_note?: string | null;
          affected_services?: string[] | null;
          business_impact?: 'none' | 'low' | 'medium' | 'high' | 'critical' | null;
          estimated_affected_users?: number | null;
          escalation_level?: number;
          escalated_at?: string | null;
          escalated_to?: string[] | null;
          notifications_sent?: any | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          alert_rule_id?: string;
          integration_id?: string;
          triggered_at?: string;
          resolved_at?: string | null;
          duration_minutes?: number | null;
          alert_message?: string;
          severity?: string;
          trigger_value?: number | null;
          threshold_value?: number | null;
          status?: 'open' | 'acknowledged' | 'resolved' | 'suppressed';
          acknowledged_by?: string | null;
          acknowledged_at?: string | null;
          resolved_by?: string | null;
          resolution_note?: string | null;
          affected_services?: string[] | null;
          business_impact?: 'none' | 'low' | 'medium' | 'high' | 'critical' | null;
          estimated_affected_users?: number | null;
          escalation_level?: number;
          escalated_at?: string | null;
          escalated_to?: string[] | null;
          notifications_sent?: any | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      integration_dependencies: {
        Row: {
          id: string;
          integration_id: string;
          depends_on_integration_id: string;
          dependency_type: string;
          description: string | null;
          failure_propagates: boolean;
          propagation_delay_minutes: number;
          created_at: string;
        };
        Insert: {
          id?: string;
          integration_id: string;
          depends_on_integration_id: string;
          dependency_type: string;
          description?: string | null;
          failure_propagates?: boolean;
          propagation_delay_minutes?: number;
          created_at?: string;
        };
        Update: {
          id?: string;
          integration_id?: string;
          depends_on_integration_id?: string;
          dependency_type?: string;
          description?: string | null;
          failure_propagates?: boolean;
          propagation_delay_minutes?: number;
          created_at?: string;
        };
      };
      maintenance_windows: {
        Row: {
          id: string;
          title: string;
          description: string | null;
          maintenance_type: string;
          scheduled_start: string;
          scheduled_end: string;
          actual_start: string | null;
          actual_end: string | null;
          affected_integrations: string[];
          affected_services: string[] | null;
          expected_impact: 'none' | 'partial' | 'full';
          impact_description: string | null;
          notify_users: boolean;
          notification_advance_hours: number;
          notifications_sent: boolean;
          status: 'scheduled' | 'in_progress' | 'completed' | 'cancelled';
          requires_approval: boolean;
          approved_by: string | null;
          approved_at: string | null;
          created_by: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          title: string;
          description?: string | null;
          maintenance_type?: string;
          scheduled_start: string;
          scheduled_end: string;
          actual_start?: string | null;
          actual_end?: string | null;
          affected_integrations: string[];
          affected_services?: string[] | null;
          expected_impact?: 'none' | 'partial' | 'full';
          impact_description?: string | null;
          notify_users?: boolean;
          notification_advance_hours?: number;
          notifications_sent?: boolean;
          status?: 'scheduled' | 'in_progress' | 'completed' | 'cancelled';
          requires_approval?: boolean;
          approved_by?: string | null;
          approved_at?: string | null;
          created_by?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          title?: string;
          description?: string | null;
          maintenance_type?: string;
          scheduled_start?: string;
          scheduled_end?: string;
          actual_start?: string | null;
          actual_end?: string | null;
          affected_integrations?: string[];
          affected_services?: string[] | null;
          expected_impact?: 'none' | 'partial' | 'full';
          impact_description?: string | null;
          notify_users?: boolean;
          notification_advance_hours?: number;
          notifications_sent?: boolean;
          status?: 'scheduled' | 'in_progress' | 'completed' | 'cancelled';
          requires_approval?: boolean;
          approved_by?: string | null;
          approved_at?: string | null;
          created_by?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      integration_baselines: {
        Row: {
          id: string;
          integration_id: string;
          baseline_start_date: string;
          baseline_end_date: string;
          baseline_type: string;
          baseline_response_time_ms: number | null;
          baseline_uptime_percentage: number | null;
          baseline_error_rate: number | null;
          baseline_requests_per_hour: number | null;
          response_time_std_dev: number | null;
          uptime_std_dev: number | null;
          sample_size: number | null;
          confidence_level: number;
          is_active: boolean;
          last_calculated: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          integration_id: string;
          baseline_start_date: string;
          baseline_end_date: string;
          baseline_type?: string;
          baseline_response_time_ms?: number | null;
          baseline_uptime_percentage?: number | null;
          baseline_error_rate?: number | null;
          baseline_requests_per_hour?: number | null;
          response_time_std_dev?: number | null;
          uptime_std_dev?: number | null;
          sample_size?: number | null;
          confidence_level?: number;
          is_active?: boolean;
          last_calculated?: string;
          created_at?: string;
        };
        Update: {
          id?: string;
          integration_id?: string;
          baseline_start_date?: string;
          baseline_end_date?: string;
          baseline_type?: string;
          baseline_response_time_ms?: number | null;
          baseline_uptime_percentage?: number | null;
          baseline_error_rate?: number | null;
          baseline_requests_per_hour?: number | null;
          response_time_std_dev?: number | null;
          uptime_std_dev?: number | null;
          sample_size?: number | null;
          confidence_level?: number;
          is_active?: boolean;
          last_calculated?: string;
          created_at?: string;
        };
      };
      integration_system_config: {
        Row: {
          id: string;
          config_key: string;
          config_value: any;
          config_type: string;
          description: string | null;
          validation_schema: any | null;
          is_encrypted: boolean;
          last_updated_by: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          config_key: string;
          config_value: any;
          config_type?: string;
          description?: string | null;
          validation_schema?: any | null;
          is_encrypted?: boolean;
          last_updated_by?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          config_key?: string;
          config_value?: any;
          config_type?: string;
          description?: string | null;
          validation_schema?: any | null;
          is_encrypted?: boolean;
          last_updated_by?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      user_profiles: {
        Row: {
          id: string;
          email: string;
          role: string;
          full_name: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id: string;
          email: string;
          role: string;
          full_name?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          email?: string;
          role?: string;
          full_name?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      user_activity_log: {
        Row: {
          id: string;
          user_id: string;
          action: string;
          resource_type: string | null;
          resource_id: string | null;
          metadata: any | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          action: string;
          resource_type?: string | null;
          resource_id?: string | null;
          metadata?: any | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          action?: string;
          resource_type?: string | null;
          resource_id?: string | null;
          metadata?: any | null;
          created_at?: string;
        };
      };
    };
    Views: {
      [_ in never]: never;
    };
    Functions: {
      [_ in never]: never;
    };
    Enums: {
      [_ in never]: never;
    };
  };
}