name = "ganger-batch-closeout"
main = "worker-simple.js"
compatibility_date = "2024-06-12"
compatibility_flags = ["nodejs_compat"]

[env.production]
name = "ganger-batch-closeout-prod"
# Routes handled by staff-router.js at staff.gangerdermatology.com/batch-closeout

[env.staging]
name = "ganger-batch-closeout-staging"

# Environment variables
[vars]
ENVIRONMENT = "production"
APP_NAME = "Batch Closeout System"