name = "ganger-ai-receptionist-v2"
main = "worker.js"
compatibility_date = "2024-01-01"

[[r2_buckets]]
binding = "AI_RECEPTIONIST_BUCKET"
bucket_name = "ganger-ai-receptionist"
preview_bucket_name = "ganger-ai-receptionist-preview"

[env.production]
name = "ganger-ai-receptionist-v2"

[[env.production.r2_buckets]]
binding = "AI_RECEPTIONIST_BUCKET"
bucket_name = "ganger-ai-receptionist-production"

[env.staging]
name = "ganger-ai-receptionist-staging"

[[env.staging.r2_buckets]]
binding = "AI_RECEPTIONIST_BUCKET"
bucket_name = "ganger-ai-receptionist-staging"