name: Clear Vercel Cache

on:
  workflow_dispatch:
    inputs:
      app_name:
        description: 'App name to clear cache for (or "all" for all apps)'
        required: true
        default: 'eos-l10'
        type: choice
        options:
          - eos-l10
          - batch-closeout
          - integration-status
          - pharma-scheduling
          - socials-reviews
          - ai-receptionist
          - call-center-ops
          - medication-auth
          - component-showcase
          - all

jobs:
  clear-cache:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Clear Vercel Cache
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_TEAM_ID: ${{ secrets.VERCEL_TEAM_ID }}
        run: |
          if [ "${{ github.event.inputs.app_name }}" = "all" ]; then
            ./scripts/clear-vercel-cache.sh --all
          else
            ./scripts/clear-vercel-cache.sh ${{ github.event.inputs.app_name }}
          fi

  clear-cache-api:
    runs-on: ubuntu-latest
    name: Clear Cache via API
    steps:
      - name: Clear Cache for ${{ github.event.inputs.app_name }}
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_TEAM_ID: ${{ secrets.VERCEL_TEAM_ID }}
        run: |
          # Function to clear cache via API
          clear_cache() {
            local app=$1
            local project_name="ganger-$app"
            
            echo "Clearing cache for $project_name..."
            
            # Trigger deployment with cache disabled
            curl -X POST \
              -H "Authorization: Bearer $VERCEL_TOKEN" \
              -H "Content-Type: application/json" \
              "https://api.vercel.com/v13/deployments?teamId=$VERCEL_TEAM_ID&forceNew=1&withCache=0" \
              -d "{
                \"name\": \"$project_name\",
                \"gitSource\": {
                  \"type\": \"github\",
                  \"repo\": \"acganger/ganger-platform\",
                  \"ref\": \"main\"
                }
              }"
          }
          
          if [ "${{ github.event.inputs.app_name }}" = "all" ]; then
            apps=("eos-l10" "batch-closeout" "integration-status" "pharma-scheduling" "socials-reviews" "ai-receptionist" "call-center-ops" "medication-auth" "component-showcase")
            for app in "${apps[@]}"; do
              clear_cache "$app"
              sleep 2
            done
          else
            clear_cache "${{ github.event.inputs.app_name }}"
          fi