name: 🚀 Deploy Handouts

on:
  push:
    branches: [ main ]
    paths: [ 'apps/handouts/**' ]
  workflow_dispatch:

env:
  NODE_VERSION: '20'
  PNPM_VERSION: '8'

jobs:
  deploy-handouts:
    name: Build and Deploy Handouts
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          run_install: false

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build handouts
        run: |
          cd apps/handouts
          pnpm run build:cloudflare
        env:
          NEXT_PUBLIC_SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          NEXT_PUBLIC_SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}

      - name: Deploy Worker
        run: |
          cd apps/handouts
          npx wrangler deploy --env production
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}

      - name: Deployment Success
        run: |
          echo "✅ Handouts deployed successfully to Workers!"
          echo "🌐 Access via: https://staff.gangerdermatology.com/handouts"
          echo "🌐 Worker URL: https://ganger-handouts-prod.workers.dev"