name: 🎯 Deploy Single App

on:
  workflow_dispatch:
    inputs:
      app:
        description: 'App to deploy'
        required: true
        type: choice
        options:
          - inventory
          - handouts
          - eos-l10
          - batch-closeout
          - compliance-training
          - clinical-staffing
          - config-dashboard
          - integration-status
          - ai-receptionist
          - call-center-ops
          - medication-auth
          - pharma-scheduling
          - checkin-kiosk
          - socials-reviews
          - component-showcase
          - platform-dashboard
          - staff
      environment:
        description: 'Environment'
        required: true
        default: 'production'
        type: choice
        options:
          - production
          - preview

jobs:
  deploy:
    name: 🚀 Deploy ${{ github.event.inputs.app }}
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v2
        with:
          version: 8

      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build application
        run: pnpm run build --filter=@ganger/${{ github.event.inputs.app }}...
        env:
          NEXT_PUBLIC_SUPABASE_URL: ${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}
          NEXT_PUBLIC_SUPABASE_ANON_KEY: ${{ secrets.NEXT_PUBLIC_SUPABASE_ANON_KEY }}
          SKIP_ENV_VALIDATION: true

      - name: Deploy to Vercel
        id: deploy
        uses: amondnet/vercel-action@v25
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ github.event.inputs.app == 'inventory' && secrets.VERCEL_PROJECT_ID_INVENTORY || github.event.inputs.app == 'handouts' && secrets.VERCEL_PROJECT_ID_HANDOUTS || github.event.inputs.app == 'eos-l10' && secrets.VERCEL_PROJECT_ID_EOS_L10 || github.event.inputs.app == 'batch-closeout' && secrets.VERCEL_PROJECT_ID_BATCH_CLOSEOUT || github.event.inputs.app == 'compliance-training' && secrets.VERCEL_PROJECT_ID_COMPLIANCE_TRAINING || github.event.inputs.app == 'clinical-staffing' && secrets.VERCEL_PROJECT_ID_CLINICAL_STAFFING || github.event.inputs.app == 'config-dashboard' && secrets.VERCEL_PROJECT_ID_CONFIG_DASHBOARD || github.event.inputs.app == 'integration-status' && secrets.VERCEL_PROJECT_ID_INTEGRATION_STATUS || github.event.inputs.app == 'ai-receptionist' && secrets.VERCEL_PROJECT_ID_AI_RECEPTIONIST || github.event.inputs.app == 'call-center-ops' && secrets.VERCEL_PROJECT_ID_CALL_CENTER_OPS || github.event.inputs.app == 'medication-auth' && secrets.VERCEL_PROJECT_ID_MEDICATION_AUTH || github.event.inputs.app == 'pharma-scheduling' && secrets.VERCEL_PROJECT_ID_PHARMA_SCHEDULING || github.event.inputs.app == 'checkin-kiosk' && secrets.VERCEL_PROJECT_ID_CHECKIN_KIOSK || github.event.inputs.app == 'socials-reviews' && secrets.VERCEL_PROJECT_ID_SOCIALS_REVIEWS || github.event.inputs.app == 'component-showcase' && secrets.VERCEL_PROJECT_ID_COMPONENT_SHOWCASE || github.event.inputs.app == 'platform-dashboard' && secrets.VERCEL_PROJECT_ID_PLATFORM_DASHBOARD || github.event.inputs.app == 'staff' && secrets.VERCEL_PROJECT_ID_STAFF || '' }}
          vercel-args: ${{ github.event.inputs.environment == 'production' && '--prod' || '' }}
          working-directory: apps/${{ github.event.inputs.app }}
          scope: ${{ secrets.VERCEL_TEAM_ID }}

      - name: Deployment Summary
        run: |
          echo "✅ Deployment Complete!"
          echo "App: ${{ github.event.inputs.app }}"
          echo "Environment: ${{ github.event.inputs.environment }}"
          echo "URL: ${{ steps.deploy.outputs.url }}"
          echo ""
          echo "🔗 Deployment URL: ${{ steps.deploy.outputs.url }}"

      - name: Update Staff Portal (if not deploying staff itself)
        if: github.event.inputs.app != 'staff' && github.event.inputs.environment == 'production'
        run: |
          echo "📝 Note: You may need to update the staff portal rewrites if this is a new deployment URL"
          echo "Run the 'Update Staff Portal Rewrites' workflow if needed"