name: Update Edge Config

on:
  # Manual trigger
  workflow_dispatch:
  
  # Trigger after deployment workflows complete
  workflow_run:
    workflows: ["Deploy Apps"]
    types:
      - completed
  
  # Or trigger on push to main if you want automatic updates
  # push:
  #   branches:
  #     - main
  #   paths:
  #     - 'scripts/update-edge-config.js'
  #     - 'apps/**/vercel.json'

jobs:
  update-edge-config:
    name: Update Edge Config Routes
    runs-on: ubuntu-latest
    
    # Only run on successful deployments or manual trigger
    if: ${{ github.event_name == 'workflow_dispatch' || github.event.workflow_run.conclusion == 'success' }}
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      
      - name: Update Edge Config
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_TEAM_ID: ${{ secrets.VERCEL_TEAM_ID }}
        run: |
          echo "Updating Edge Config with latest app URLs..."
          node scripts/update-edge-config.js
      
      - name: Notify on failure
        if: failure()
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '❌ Edge Config update failed! Check the [workflow logs](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}).'
            })